var questions = [["In the key of C Major, what is the interval from C-G?", "5th", "4th", "6th", "7th"],
["In the key of G Major, what is the interval from G-C?", "4th", "5th", "6th", "7th"],
["In the key of F Major, what is the interval from F-G?", "2nd", "4th", "6th", "7th"],
["In the key of Bb Major, what is the interval from Bb-G?", "6th", "4th", "3rd", "7th"],
["In the key of Eb Major, what is the interval from Eb-F?", "2nd", "4th", "6th", "3rd"],
["In the key of Ab Major, what is the interval from Ab-G?", "7th", "4th", "6th", "2nd"],
["In the key of Db Major, what is the interval from Db-Bb?", "6th", "4th", "3rd", "7th"],
["In the key of Gb Major, what is the interval from Gb-Ab?", "Major 2nd", "Minor 2nd", "Major 6th", "Major 7th"],
["In the key of Cb Major, what is the interval from Cb-G?", "Augmented 5th", "Perfect 5th", "Major 5th", "Minor 5th"],
["In the key of D Major, what is the interval from D-G?", "4th", "5th", "6th", "7th"],
["In the key of A Major, what is the interval from A-B#?", "Augmented 2nd", "Major 2nd", "6th", "7th"],
["In the key of E Major, what is the interval from E-F#?", "Major 2nd", "Perfect 2nd", "Diminished 3rd", "Major 7th"],
["In the key of B Major, what is the interval from B-G#?", "Perfect 5th", "Perfect 4th", "Major 3rd", "Unison"],
["In the key of F# Major, what is the interval from F#-G#?", "Major 2nd", "Minor 4th", "Minor 6th", "Perfect 7th"],
["In the key of C# Major, what is the interval from C#-G#?", "Perfect 5th", "Perfect 4th", "Major 6th", "Minor 7th"],
["In the key of C Minor, what is the interval from C-G?", "Perfect 5th", "Major 5th", "Minor 5th", "Diminished 5th"],
["In the key of A Minor, what is the interval from A-G?", "Minor 7th", "4th", "6th", "Major 7th"],
["In the key of D Minor, what is the interval from D-Bb?", "Minor 6th", "4th", "Major 6th", "7th"],
["In the key of G Minor, what is the interval from G-G?", "Octave", "Diminished 9th", "Augmented 7th", "Major 7th"],
["In the key of C Minor, what is the interval from C-Eb?", "Minor 3rd", "Diminshed 4th", "Major 3rd", "Augmented 2nd"],
["In the key of F Minor, what is the interval from F-Bb?", "4th", "3rd", "6th", "7th"],
["In the key of Bb Minor, what is the interval from Bb-F?", "5th", "4th", "6th", "7th"],
["In the key of A Minor, what is the interval from A-C?", "3rd", "2nd", "6th", "7th"],
["In the key of Ab Minor, what is the interval from Ab-G?", "Major 7th", "Minor 7th", "Augmented 7th", "Diminished 8th"],
["Which chords form an Authentic/Perfect Cadence?", "V-I", "VI-I", "II-I or I-V", "V-VI"],
["Which chords can form an Imperfect Cadence?", "I-V, II-V, IV-V & VI-V", "V-VI", "III-VI", "IV-I"],
["Which chords can form an Interrupted/Deceptive Cadence?", "V-II", "V-VI", "V-IV", "All"],
["Which triad in a Minor key is Major?", "V", "II", "III", "VII"],
["Which triads in a Major key are Minor?", "II, III & VI", "V & VI", "VII", "IV & V"],
["Which triad in any key is Diminished?", "VII", "Vb", "II", "VI"],
["Which triad in a Minor key is Augmented?", "III", "VII", "VI", "II"],
["Which triad is Major in a Minor key and Minor in a Major key?", "VI", "II", "III", "V"],
["Which cadence is also known as the 'Amen' Cadence?", "Plagal", "Perfect", "Interrupted", "Imperfect"],
["In an Interrupted Cadence (V-VI), which voice(s) should rise?", "Bass & Leading Note", "Fifth", "Third", "Root" ], 
["Which chord(s) sound well preceding an Authentic Cadence?", "II or VI in root position & cadential chords in first inversion", "III", "VII", "None"], 
["Which chords form the cadences in which the upper parts should move in contrary motion to the bass?", "II-V, IV-V & V-VI", "V-VI", "II-IV", "I-IV"], 
["When writing 4 part harmony, which part is best to double in any chord other than VI?", "Root", "Third", "Sixth", "Fifth"], 
["When writing 4 part harmony, which part other than the root should you never omit from cadences?", "Third", "Fifth", "Seventh", "Sixth"], 
["Which note should always rise to the tonic?", "Leading Note", "Dominant", "Supertonic", "Subdominant"], 
["Which are the primary triads?", "I, IV & V", "II & IV", "IV & V", "III & VII"], 
["Which first inversion chord(s) can lead into a cadence?", "Ib, IIb, IVb & VIIb", "Vb", "IIIb", "IIb & VIb"],
["When writing 4 part harmony, in which chord(s) can you double the Minor third?", "II, VI & VIIb", "V", "I", "V & I"], 
["Which cadence contains the chords that should have a descending third from the root of V to the 5th of VI?", "Interrupted", "Imperfect", "Authentic", "Plagal"],
["When leading into a cadence, if using cadential chords, which inversion should they be in?", "1st", "2nd", "3rd", "Root Position"],
["Which chord should harmonise an anacrusis?", "V or Vb (occasionally I or Ib)", "II", "VII", "IV"],
["When writing 4 part harmony, which note should never be doubled?", "Leading Note", "Tonic", "Fifth", "Third"],
["When a piece in a minor key ends with a major chord it is termed?", "Tierce de Picardie/Picardy 3rd", "Modulation",
 "Transposition", "Consonance"],
["When a musician plays alone it is called a?", "Solo", "Duet", "Trio", "Quartet"],
["When 2 musicians play together?", "Duet", "Trio", "Quartet", "Quintet"],
["When 3 musicians play together it is called a?", "Trio", "Solo", "Duet",  "Quartet"],
["When 4 musicians play together it is called a?", "Quartet", "Solo", "Sextet", "Trio"],
["When 5 musicians play together it is called a?", "Quintet", "Duet", "Trio", "Quartet"],
["When 6 musicians play together it is called a?", "Sextet", "Duet", "Trio", "Quartet"],
["Which chords form the 'Amen' cadence?", "IV-I", "V-I", "V-VI", "II-V"],
["An inverted 5th becomes which inverval?", "4th", "5th", "6th", "Unison"],
["An inverted 6th becomes which inverval?", "3rd", "5th", "6th", "Unison"],
["An inverted 7th becomes which inverval?", "2nd", "5th", "6th", "Unison"],
["An inverted 3rd becomes which inverval?", "6th", "5th", "6th", "Unison"],
["An inverted 2nd becomes which inverval?", "7th", "5th", "6th", "Unison"],
["An inverted 4th becomes which inverval?", "5th", "5th", "6th", "Unison"],
["When inverted, a Perfect 5th becomes which inverval?", "Perfect 4th", "Diminished 5th", "Augmented 5th", "Unison"],
["When inverted, a Major 6th becomes which inverval?", "Minor 3rd", "Major 3rd", "Minor 6th", "Major 6th"],
["When inverted, a Major 7th becomes which inverval?", "Minor 2nd", "Minor 5th", "Major 2nd", "Unison"],
["When inverted, a Minor 3rd becomes which inverval?", "Major 6th", "Perfect 6th", "Minor 6th", "Unison"],
["When inverted, a Minor 2nd becomes which inverval?", "Major 7th", "Minor 7th", "Dimished 7th", "Augmented 7th"],
["When inverted, a Perfect 4th becomes which inverval?", "Perfect 5th", "Diminished 5th", "6th", "Major 2nd"],
["When inverted, an Augmented 5th becomes which interval?", "Diminished 4th", "Diminished 5th", "Augmented 4th", "Augmented 5th"],
["Which degrees are raised in the ascending Melodic Minor scale?", "6th & 7th", "5th & 6th", "2nd & 7th", "3rd & 6th"],
["Which note is raised in the Harmonic Minor scale?", "7th", "3rd", "6th", "8th"],
["Which cadences should be used to indicate the music will continue?", "I-V, II-V, IV-V, VI-V or V-VI", "V-I", "VI-I", "IV-I"],
["Which chords form the cadences that should be used to conclude a piece?", "IV-I or V-I", "I-V", "VI-I", "VII-I"],
["What is another name for 'chord of the sixth'?", "First Inversion", "Tritone", "Tierce de Picardie", "Root Position"],
["When writing 4 part harmony, which intervals must be avoided between adjacent chords?", "Consecutive (parallel) 5ths & 8ths", "Consecutive Thirds", "Fourths", "All should be avoided"],
["Which chord is Diminished in a Minor key only?", "II", "V", "VII", "III"],
["How many quavers in a crotchet?", "2", ".5", "4", "6"],
["How many semi-quavers in a crotchet?", "4", "5", "6", "8"],
["How many crotchets in a breve?", "8", "4", "6", ".5"],
["How many crotchets in a semibreve?", "4", "6", "3", "2"],
["How many crotchets in a dotted minim?", "3", "1", "1.5", "2"],
["How many crotchets in a quaver?", ".5", "1", "2", "3"],
["How many crotchets in a minim?", "2", "1", "3", ".5"],
["How many crotchet beats in a dotted crotchet?", "1.5", "2", "3", "4"],
["How many crotchets in 3 minims?", "6", "3", "2.5", "9"],
["How many semi-quavers in a minim?", "8", "4", "2", "6"],
["How many crotchets in a breve?", "8", "4", "2", "6"],
["How many quavers in a dotted crotchet?", "3", "4", "2", "6"],
["How many semi-quavers in a dotted crotchet?", "6", "4", "2", "3"],
["How many crotchets in 1 semibreve tied to 1 crotchet?", "5", "6", "10", "4"],
["What is the first degree of the scale?", "Tonic", "Supertonic", "Mediant", "Upper Tonic"],
["What is the second degree of the scale?", "Supertonic", "Subdominant", "Submediant", "Leading Note"],
["What is the third degree of the scale?", "Mediant", "Supertonic", "Supermediant", "Dominant"],
["What is the fourth degree of the scale?", "Subdominant", "Tonic", "Submediant", "Leading Note"],
["What is the fifth degree of the scale?", "Dominant", "Subdominant", "Submediant", "Leading Note"],
["What is the sixth degree of the scale?", "Submediant", "Supertonic", "Mediant", "Dominant"],
["What is the seventh degree of the scale?", "Leading Note", "Supertonic", "Mediant", "Dominant"],
["Which of the dances always begins on the 3rd beat of the bar?", "Gavotte", "Allemande", "Sarabande", "Minuet"],
["What is the technical name for the fourth degree of the scale?", "Subdominant", "Mediant", "Tonic", "Supertonic"],
["Which of these musical periods came first?", "Baroque", "Classical", "Romantic", "Modern"],
["Which of these musical periods was the second-most recent in history?", "Romantic", "Baroque", "Classical", "Modern"],
["Which of these musical periods is the most recent in history?", "Modern", "Classical", "Romantic", "Baroque"],
["Which of these musical periods was the earliest given?", "Renaissance", "Classical", "Romantic", "Baroque"],
["Which of these musical periods was the earliest given?", "Medieval", "Classical", "Renaissance", "Baroque"],
["Which of these periods came second in the list given?", "Classical", "Baroque", "Romantic", "Modern"],
["What is the term for making music up as you are playing (usually as a solo)?", "Improvisation", "Modulation", "Syncopation", "Transposition"],
["What is the term for music which is deliberately in front of the beat?", "Syncopation", "Modulation", "Improvisation", "Transposition"],
["What is is the term for taking a sound recording and reusing it as a part of another song?", "Sampling", "Syncopation", "Transposition", "Modulation"],
["What is the term for taking a melody and re-writing in a different key?", "Transposition", "Sampling", "Syncopation", "Sostenuto"],
["In which country did Opera originate?", "Italy", "United Kingdom", "France", "China"],
["Who composed 'The Magic Flute'?", "Mozart", "Handel", "Stravinsky", "Holst"],
["Who composed 'The Planets'?", "Holst", "Stravinsky", "Bach", "Beethoven"],
["Who composed 'The Nutcracker'?", "Tchaikovsky", "Holst", "Bach", "Grieg"],
["Who composed 'Peer Gynt'?", "Grieg", "Tchaikovsky", "Holst", "Handel"],
["Which are the secondary triads?", "II, III, VI & VII", "I, II", "II & IV", "IV & V"],
["Which interval can be used providing the FOLLOWING note is pitched within that interval?", "Diminished", "Augmented", "Tritone", "Major 7th"],
["Which interval can only be used when the PRECEDING note is pitched within it?", "Octave", "Unison", "Tritone", "Major 7th"],
["Which degree of the scale ought to be used for an anacrusis?", "Dominant or Tonic", "Supertonic or Tonic", "Submediant or Dominant", "Mediant or Dominant"],
["Which note should always FOLLOW use of the leading note?", "Tonic", "Mediant", "Dominant", "Subdominant"],
["What is the term used to describe a series of intervals repeated at a different pitch?", "Sequence", "Melody", "Harmony", "Sound"],
["What is the term used to describe music where each part forms a melody in it's own right?", "Counterpoint, contrapuntal or polyphonic", "Monophonic", "Homophonal", "Chordal"],
["What is the term used to describe when two parts move in opposite directions in pitch?", "Contrary motion", "Oblique motion", "Similar motion", "Distancing"],
["What is the term used to describe music that has one stationary part while another part moves in pitch?", "Oblique motion", "Similar motion", "Ordinal motion", "Contrary motion"],
["What is the term used to describe music that has the pitch of two parts move in the same direction?", "Similar motion", "Oblique motion", "Contrary motion", "Homophonic"],
["When a melody begins part way through a bar this is called?", "Anacrusis", "Turn", "Mordant", "Trill"],
["Where there is no anacrusis, a melody begins and ends on the?", "Tonic", "Dominant", "Subdominant", "Supertonic"],
["What is the term used to describe a melody that uses turns, mordants or trills?", "Ornamented or Decorated", "Difficult", "Advanced", "Classical"],
["What is the term used to describe harmonisation that primarily consists of chords?", "Homophonic", "Polyphonic", "Monophonic", "Semiotic"],
["What interval separates the notes in a chromatic scale?", "Semitone", "Tone", "Both", "Neither"],
["What is the relative key of F Major?", "D Minor", "B Minor", "D Minor", "C Minor"],
["What is the relative key of Cb Major?", "Ab Minor", "Cb Minor", "Eb Minor", "F Minor"],
["What is the relative key of Gb Major?", "Bb Minor", "Gb Minor", "C Minor", "Eb Minor"],
["What is the relative key of Db Major?", "Bb Minor", "Db Minor", "A Minor", "F Minor"],
["What is the relative key of Ab Major?", "F Minor", "A Minor", "Ab Minor", "C Minor"],
["What is the relative key of Eb Major?", "C Minor", "Eb Minor", "D Minor", "A Minor"],
["What is the relative key of Bb Major?", "G Minor", "A Minor", "F Minor", "D Minor"],
["What is the relative key of C# Major?", "A# Minor", "G Minor", "E Minor", "F Minor"],
["What is the relative key of F# Major?", "D# Minor", "F# Minor", "A Minor", "G Minor"],
["What is the relative key of B Major?", "G# Minor", "B Minor", "D Minor", "C# Minor"],
["What is the relative key of E Major?", "C# Minor", "C Minor", "A Minor", "F Minor"],
["What is the relative key of A Major?", "F# Minor", "A Minor", "D Minor", "B Minor"],
["What is the relative key of D Major?", "B Minor", "F# Minor", "Bb Minor", "F Minor"],
["What is the relative key of G Major?", "E Minor", "A Minor", "B Minor", "C Minor"],
["What is the term for a note foreign to the key signature?", "Accidental", "Occidental", "Alien", "Mordant"],
["Which ornament takes it's value from the preceding note or rest?", "Acciaccatura", "Mordant", "Appoggiatura", "Turn"],
["Which ornament takes it's value from the note following?", "Appoggiatura", "Acciaccatura", "Mordant", "Staccato"],
["What is another word for the musical term 'leaning note'?", "Appoggiatura", "Acciaccatura", "Mordant", "Staccato"],
["What is another word for the musical term 'crushed note'?", "Acciaccatura", "Leaning Note", "Appoggiatura", "Turn"],
["What is the English meaning of allargando?", "getting slower and broader", "more movement", "very lively", "less movement"],
["What is the English meaning of piu mosso?", "more movement", "very lively", "less movement", "sustained"],
["What is the English meaning of meno mosso", "less movement", "lightly", "sustained", "broadly"],
["What is the English meaning of sehr lebhaft?", "very lively", "lightly", "sustained", "less movement"],
["What is the English meaning of sostenuto?", "sustained", "lightly", "broadly", "dying away"],
["What is the English meaning of leggiero?", "lightly", "broadly", "dying away", "with agitaton"],
["What is the English meaning of largamente?", "broadly", "extremely fast or as fast as possible", "with agitaton", "calmly"],
["What is the English meaning of larghetto?", "rather broadly", "with movement", "softer and slower", "with agitaton"],
["What is the English meaning of prestissimo?", "extremely fast or as fast as possible", "with movement", "calmly", "sadly"],
["What is the English meaning of con moto?", "with movement", "softer and slower", "with agitaton", "calmly"],
["What is the English meaning of calando?", "softer and slower", "with agitaton", "sadly", "cheerfully"],
["What is the English meaning of morendo?", "dying away", "loud then immediately soft", "with agitaton", "calmly"],
["What is the English meaning of fortepiano (fp)?", "loud then immediately soft", "with agitaton", "calmly", "sadly"],
["What is the English meaning of sforzando (sf) (sfz)?", "played with a strong accent", "with agitaton", "sadly", "softly"],
["What is another word for the term 'shake'?", "Trill", "Mordant", "Turn", "Leaning Note"],
["What is the English meaning of loco?", "at normal pitch (after 8va)", "with grace", "move on at once", "with force"],
["What is the English meaning of ad libitum?", "at your own pleasure", "with feeling", "with grace", "move on at once"],
["What is the English meaning of tre corde (TC)?", "release the soft pedal", "with force", "with grace", "lyrically"],
["What is the English meaning of une corde (UC)?", "use soft pedal", "with force", "with grace", "faster"],
["What is the English meaning of main gauche (MG)?", "left hand", "", "with grace", "with spirit"],
["What is the English meaning of main droite (MD)?", "right hand", "with grace", "slow", "faster"],
["What is the English meaning of risoluto?", "with resolution", "faster", "slower", "softer"],
["What is the English meaning of dolce?", "soft and sweet", "with force", "louder", "faster"],
["What is the English meaning of con forza?", "with force", "with grace", "speed up", "softer"],
["What is the English meaning of con grazia?", "with grace", "speed up", "louder", "with spirit"],
["What is the English meaning of con anima?", "with feeling", "softer", "slower", "faster"],
["What is the English meaning of tranquillo?", "calmly", "faster", "with spirit", "with agitation"],
["What is the English meaning of animato?", "with animation", "with grace", "attack", "in an undertone"],
["What is the English meaning of attacca?", "move on at once", "in a singing style", "soft", "with grace"],
["What is the English meaning of agitato?", "with agitaton", "with grace", "twice as fast", "twice as slow"],
["What is the English meaning of con brio?", "with spirit", "with sadness", "louder", "faster"],
["What is the English meaning of ben marcato?", "well marked", "with spirit", "softly", "repeat"],
["What is the English meaning of tempo commodo?", "at a comfortable speed", "softer", "slower", "louder"],
["What is the English meaning of tempo guisto?", "at a consistent speed", "accelerate", "slow", "louder"],
["What is the English meaning of l'istesso tempo?", "at the same speed", "faster", "slowly", "accelerate"],
["What is the English meaning of non troppo?", "not too much", "happily", "sadly", "not at all"],
["What is the English meaning of rubato?", "with some freedom in the time", "well marked", "with spirit", "strongly"],
["What is the English meaning of stringendo?", "pressing on faster", "dying away", "gracefully", "slowly"],
["What is the English meaning of perdendosi?", "fading away", "strongly", "playfully", "quickly"],
["What is the English meaning of smorzando?", "dying away", "louder", "a little", "as if"],
["What is the English meaning of rinforzando (rfz.) (rf.)?", "reinforcing the tone", "repeat", "sofly", "gracefully"],   
["What is the English meaning of pesante?", "heavily", "calmly", "a little", "with spirit"],
["What is the English meaning of cantando?", "in a singing style", "softly", "forcefully", "slowly"],
["What is the English meaning of tenuto (ten.)?", "held", "repeat", "softly", "pleasantly"],
["What is the English meaning of piacevole?", "pleasant, agreeable", "pluck the string", "strongly", "softly"],
["What is the English meaning of portamento?", "glide smoothly from one note to the next", "playfully", "strongly", "repeat"],
["What is the English meaning of dolente?", "sadly", "as if", "playfully", "strongly"],
["What is the English meaning of doloroso?", "plaintively", "playfully", "accelerate", "repeat"],
["What is the English meaning of sotto voce?", "in an undertone", "playfully", "accelerate", "louder"],
["What is the English meaning of giacoso?", "gay, merry", "dying away", "louder", "sadly"],
["What is the English meaning of grazioso?", "gracefully", "faster", "singing style", "heavily"],
["What is the English meaning of assai?", "very", "as if", "fading away", "heavily"],
["What is the English meaning of quasi?", "as if", "playfully", "dying away", "held"],
["What is the English meaning of scherzando?", "playfully", "heavily", "sadly", "faster"],
["What is the English meaning of subito (sub)?", "suddenly", "pluck the string", "faster", "louder"],
["What is the English meaning of sul ponticello (sul pont)?", "bow on or near the bridge", "quicker", "sadly", "heavily"],
["What is the English meaning of sul tasto?", "bow on or near the finger board", "smoothly", "calmly", "faster"],
["What is the English meaning of tremolo?", "rapid bowing to produce shimmer effect", "faster", "slower", "smoothly"],
["What is the English meaning of pizzicato (pizz)?", "pluck the string", "faster", "shorter", "heavily"],
["What is the English meaning of adagio?", "slowly", "quickly", "loudly", "softly"],
["What is the English meaning of allegretto?", "moderately fast", "very fast", "slowly", "very slow"],
["What is the English meaning of andante?", "at walking pace", "fast", "very fast", "very slow"],
["What is the English meaning of lento?", "slow", "fast", "very fast", "at walking pace"],
["What is the English meaning of crescendo (<)?", "get louder", "get softer", "faster", "slower"],
["What is the English meaning of decrescendo(>)?", "get softer", "faster", "slower", "sweetly"],
["What is the English meaning of diminuendo(>)?",  "get softer", "faster", "slower", "sweetly"],
["What is the English meaning of pianissimo (pp)?", "very soft", "very loud", "soft", "loud"],
["What is the English meaning of piano (p)?", "soft", "very soft", "loud", "very loud"],
["What is the English meaning of forte (f)?", "loud", "very loud", "soft", "very soft"],
["What is the English meaning of fortissimo (ff)?", "very loud", "loud", "soft", "very soft"],
["What is the English meaning of fortepiano (fp)?", "loud then immediately soft", "loud", "soft", "very soft"],
["What is the English meaning of cantabile?", "in a singing style", "softly", "heavily", "sadly"],
["What is the English meaning of fine?", "the end", "the start", "quickly", "slowly"],
["What is the English meaning of poco?", "a little", "a lot", "sweetly", "sadly"],
["What is the English meaning of mezzo forte (mf)?", "moderately loud", "very loud", "soft", "very soft"],
["What is the English meaning of mezzo piano (mp)?", "moderately soft", "very soft", "soft", "loud"],
["What is the English meaning of moderato?", "moderately", "slowly", "fast", "loud"],
["What is the English meaning of largo?", "slow & stately", "swiftly", "softly", "sweetly"],
["What is the English meaning of presto?", "very fast", "very slow", "very quiet", "playfully"],
["What is the English meaning of vivo?", "lively", "slowly", "the start", "the end"],
["What is the English meaning of meno mosso?", "less movement", "more movement", "heartily", "loud"],
["What is the English meaning of piu mosso?", "more movement", "less movement", "the end", "fast"],
["What is the English meaning of senza?", "without", "more", "less", "forced"],
["What is the English meaning of troppo?", "too much", "too little", "without", "crazy"],
["How many lines in a staff/stave?", "5", "4", "6", "7"],
["Which clef is the highest in pitch?", "Treble", "Alto", "Tenor", "Bass"],
["Which voice is the second highest?", "Alto", "Soprano", "Tenor", "Bass"],
["Which voice is the lowest?", "Bass", "Soprano", "Alto", "Tenor"],
["Which voice is the highest?", "Soprano", "Alto", "Tenor", "Bass"],
["Which clef is known as the G clef?", "Treble", "Bass", "Alto", "Tenor"],
["Which clef is known as the C clef?", "Alto or Tenor", "Bass", "Treble", "Tenor or Bass"],
["Which clef is known as the F clef?", "Bass", "Treble", "Alto", "Bass"],
["Which instrument group does not use the C clef?", "Trumpet", "Viola", "Viola da Gamba", "Alto Trombone"],
["The correct time signature for a waltz is?", "3/4", "2/4", "4/4", "5/4"],
["The trumpet is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The trombone is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The French horn is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The baritone is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The euphonium is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The flugal horn is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The bugle is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The flute is a member of which instrument group?", "Woodwind", "String", "Percussion", "Brass"],
["The oboe is a member of which instrument group?", "Woodwind", "String", "Percussion", "Brass"],
["The clarinet is a member of which instrument group?", "Woodwind", "String", "Percussion", "Brass"],
["The bassoon is a member of which instrument group?", "Woodwind", "String", "Percussion", "Brass"],
["The piccolo is a member of which instrument group?", "Woodwind", "String", "Percussion", "Brass"],
["The violin is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The viola is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The banjo is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The lute is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The guitar is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The sitar is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The ukelele is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The harp is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The cello is a member of which instrument group?", "String", "Percussion", "Woodwind", "Brass"],
["The tenor horn is a member of which instrument group?", "Brass", "String", "Percussion", "Woodwind"],
["The kettle drum/timpani is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The side drum is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The djembe is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The marimba is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The xylophone is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The triangle is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The tambourine is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The glockenspiel is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The bodhrán is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The timbale is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The maraca is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The bongo is a member of which instrument group?", "Percussion", "String", "Woodwind", "Brass"],
["The recorder is a member of which instrument group?", "Woodwind", "String", "Brass", "Percussion"],
["The saxophone is a member of which instrument group?", "Woodwind", "String", "Brass", "Percussion"],
["What is the Supertonic of the F Major scale?", "G", "A", "Bb", "D"],
["What is the Mediant of the C Major scale?", "E", "Eb", "G", "F"],
["What is the Submediant of the A Major scale?", "F#", "C#", "B", "E"],
["What is the Leading Note of the G harmonic Minor scale?", "F#", "C", "Bb", "Eb"],
["What is the Submediant of the ascending G melodic Minor scale?", "E", "Eb", "E#", "Ex"],
["What is the Tonic of the C Minor scale?", "C", "D", "E", "F"],
["What is the Dominant of the E Minor scale?", "B", "Bb", "B#", "Bx"],
["Who wrote the 'Moonlight Sonata'?", "Beethoven", "Bach", "Haydn", "Handel"],
["Who wrote the 'Water Music'?", "Handel", "Bach", "Vivaldi", "Tchaikovsky"],
["Who wrote 'Sonata Pathetique'?", "Beethoven", "Schumann", "Schubert", "Greig"],
["Who wrote 'The Four Seasons'?", "Vivaldi", "Bach", "Handel", "Tchaikovsky"],
["Who wrote 'The 1812 Overture'?", "Tchaikovsky", "Mozart", "Bach", "Rachmaninoff"],
["Who wrote 'Bolero'?", "Ravel", "Bach", "Rachmaninoff", "Tchaikovsky"],
["Who wrote 'The Well-Tempered Clavier,'?", "Bach", "Mozart", "Liszt", "Schumann"],
["Who wrote 'Toccata and Fugue in D Minor'?", "Bach", "Hadyn", "Rachmaninoff", "Tchaikovsky"],
["What is the name for a pitch known by another note name?", "Enharmonic", "Minor", "Major", "Melody"],
["Which degrees of the major scale are separated by semi-tones?", "3-4 & 7-8", "2-3 & 5-6", "3-4 & 6-7", "1-2 & 7-8"],
["A metronome helps with?", "Tempo", "Pitch", "Harmony", "Melody"],
["How many main beats in a bar of 6/8?", "2", "8", "3", "6"],
["How many main beats in a bar of 3/4?", "1", "3", "4", "2"],
["How many main beats in a bar of 4/4?", "2", "1", "4", "3"],
["3/4 is known as?", "Simple Triple", "Compound Triple", "Simple Duple", "Compound Duple"],
["4/4 is known as?", "Simple Duple", "Simple Triple", "Compound Duple", "Compound Triple"],
["6/8 is known as?", "Compound Duple", "Compound Triple", "Simple Duple", "Simple Triple"],
["9/8 is known as?", "Compound Triple", "Compound Duple", "Simple Triple", "Simple Duple"],
["What is the term for when a melody does not begin on the first beat of the bar?", "Anacrusis", "Enharmonic", "Monotonal", "Semitonal"]
["What is another word for changing keys?", "Modulation", "Lockdown", "Cadential", "Harmony"]];