var questions = [["What is Australia's most populous city?", "Sydney", "Melbourne", "Canberra", "Perth"],
["Which date is Australia Day?", "January 26th", "April 25th", "June 8th", "December 26th"],
["In what year did Australia become a Federation?", "1901", "1788", "2000", "1903"],
["What is Australia's capital?", "Canberra", "Sydney", "Melbourne", "Brisbane"],
["What symbol is in the top left corner of the Australian flag?", "Union Jack", "Coat of Arms", "Boomerang", "Sydney Opera House"],
["What is the unofficial name for the Sydney Harbour Bridge?", "Coathanger", "Airhanger", "Cliffhanger", "Meccano Set"],
["The term 'billy' is another word for?", "kettle used when camping", "another word for billabong", "an affectionate word for Tasmanians", "a type of marsupial"],
["In which year were the Sydney Olympics?", "2000", "2001", "1995", "2005"],
["Who are the Australian mainland's original inhabitants?", "Aboriginals", "Maoris", "Dutch", "English"],
["What is the capital of New South Wales?", "Sydney", "Melbourne", "Brisbane", "Canberra"],
["A 'Banana-bender' is a?", "Resident of Queensland", "Machine for putting the bend in a banana", "Stupor induced by alcohol made from bananas", "Slang for Kangaroo"],
["What are Australia's offical colours?", "Green & Gold", "Red, White & Blue", "Red & Green", "Black & White",]
["How many territories in Australia?", "2", "3", "6", "8"],
["In Australia 'fair dinkum' means?", "true/honest", "broken", "cheerful", "irrelevant"],
["In Australia, the word 'bodgy' means?", "broken", "rare vegetable", "a surfing manoeuvre", "a cricketing term"],
["Who won the 2007 Federal election?", "Australian Labor Party", "Liberal Party of Australia", "Australian Greens", "Australian Democrats"],
["Who is the Queen of Australia?", "Queen Elizabeth II", "Dane Edna Everage", "Quentin Bryce", "Queen Elizabeth I"],
["Off which Australian coast is The Great Barrier Reef?", "Queensland", "Victoria", "Western Australia", "Tasmania"],
["Who was Australia's first Prime Minister?", "Edmond Barton", "Billy Hughes", "Robert Menzies", "Bob Hawke"],
["What is the capital of Queensland?", "Brisbane", "Cairns", "Rockhampton", "Surfers Paradise"],
["In which state or territory is Uluru?", "Northern Territory", "South Australia", "Western Australia", "Queensland"],
["Which Australian country singer sang 'The Pub with no Beer'?",  "Slim Dusty", "Shannon Noll", "Smoky Dawson", "Col Joye"],
["What is the capital of the Northern Territory?", "Darwin", "Katherine", "Alice Springs", "Uluru"],
["From which country was Captain James Cook?", "England", "France", "Holland", "Africa"],
["What is the capital of Tasmania?", "Hobart", "Derwent", "Launceston", "Melbourne"],
["In which state is the Tour Down Under?", "South Australia", "Tasmania", "Victoria", "Queensland"],
["Which of the following facts is NOT true of the Bilby?", "Bilby's are extinct", "Bilby's are omnivores", "Bilby's live in burrows", "Bilby's are nocturnal"],
["In which Australian state or territory is Thredbo?", "New South Wales", "Victoria", "Northern Territory", "Australian Capital Territory"],
["In the slang phrase 'Drinking with Pat Malone', who is Pat Malone?", "Nobody", "An Irish convict", "An Irish farmer", "A Scottish scoundrel"],
["What is the capital of Western Australia?", "Perth", "Broome", "Adelaide", "Melbourne"],
["What is Australia's smallest state?", "Tasmania", "Victoria", "Australian Capital Territory", "Kangaroo Island"],
["How many ships were in The First Fleet?", "11", "2", "1", "10"],
["In which state or territory is The Big Pineapple?", "Queensland", "New South Wales", "Victoria", "Northern Territory"],
["Which colour is on the bottom of the Aboriginal Flag (behind the sun)?", "Red", "Black", "White", "Yellow"],
["From which language is the word Australia derived?", "Latin", "Eora", "Dutch", "French"],
["In what year did the First Fleet arrive?", "1788", "1791", "1677", "1888"],
["Who bombed Darwin in WW2?", "Japan", "Germany", "Indonesia", "England"]
["In what year did Cyclone Tracy hit Darwin?", "1974", "1967", "1977", "1984"],
["In which Australian state or territory is Kernell?", "New South Wales", "Victoria", "Northern Territory", "Australian Capital Territory"],
["In what year were the Olympics in Melbourne?",  "1956", "2000", "1960", "1954"],
["Which golfer was nicknamed 'The Great White Shark'?",  "Greg Norman", "Tiger Woods", "Ian Baker-Finch", "Brett Ogle"],
["Which former Australian rugby league player has the nickname 'The King'?",  "Wally Lewis", "Wendell Sailor", "Jarryd Hayne", "Anthony Mundine"],
["In which town or city is The Big Lobster?",  "Kingston, South Australia", "Port Augusta, South Australia", "Darwin, Northern Territory", "Wyndham, Western Australia"],
["With which war is the Kokoda Track associated?", "WW2", "WW1", "Vietnam", "Boer War"],
["During which year did five yachts sink during the Sydney to Hobart Yacht Race?", "1998", "1978", "1995", "1989"],
["Which political party introduced the WorkChoices Legislation?", "The Liberal Party of Australia", "Australian Labor Party", "The Greens", "The Democrats"],
["Which animals are native to Australia?", "Wombats", "Camels", "Rabbits", "Goats"],
["Which Australian magazine offered an all-expenses divorce as a competition prize?", "Zoo Weekly", "Dolly", "Cleo", "Ralph"],
["Who founded the Liberal Party of Australia?",  "Robert Menzies", "Alfred Deakin", "Joseph Lyons", "Edmund Barton"],
["What animals are on the Australian Coat of Arms?", "Kangaroo & Emu", "Kangaroo & Wombat", "Emu & Koala", "Koala & Kangaroo"],
["In which state or territory is Australia Zoo?", "Queensland", "New South Wales", "Northern Territory", "Victoria"],
["Parramatta is a suburb of which city?", "Sydney", "Canberra", "Hobart", "Darwin"],
["In what year did Australia win The America's Cup?", "1983", "1987", "1938", "2003"],
["Subiaco is a suburb of which Australian capital?", "Perth", "Darwin", "Hobart", "Canberra"],
["In which Australian state or territory is Dubbo?", "New South Wales", "Victoria", "Northern Territory", "Australian Capital Territory"],
["Strathpine is a suburb of which Australian city?", "Brisbane", "Darwin", "Hobart", "Adelaide"],
["In what year did WW2 begin?",  "1939", "1942", "1843", "1955"],
["Which 1950's Australian runner broke the 4-minute-mile over 17 times?",  "Herb Elliott", "Robert De Castella", "Cathy Freeman", "Pat Farmer"],
["What was the theme for the 2009-10 Sydney NYE fireworks?", "Awaken the Spirit", "Above & Beyond", "The Future is Sacred", "A Land United"],
["Which Australian observatory is featured in the 2000 movie 'The Dish'?",  "Parkes", "Mount Stromlo", "Cangaroo", "Sydney"],
["What was the 'Bridge Effect' for the 2005-2006 NYE Sydney fireworks?", "Love Heart", "The Zodiac", "Rainbow Serpent", "Federation Star"],
["Who said, 'If there was a referendum tomorrow between budgie smugglers & boardies, I'd vote for boardies'?", "Kevin Rudd", "John Howard", "Paul Keating", "Bob Hawke"],
["What is the maximum permitted blood alcohol level for full car licence in Australia?",  "0.05%", "0.5%", "0.08%", "0.8%"],
["In which Australian state or territory is Mount Stromlo?", "Australian Capital Territory", "Victoria", "Northern Territory", "Queensland"],
["How many hours is the standard work week in Australia?", "38", "40", "35", "45"],
["Who lit the cauldron at the 2000 Sydney Olympics?",  "Cathy Freeman", "John Howard", "Ian Thorpe", "Pauline Hanson"],
["Which was the first Australian Football League club?",  "Melbourne Football Club", "Sydney Football Club", "Collingwood Football Club", "Carlton Football Club"],
["Which of the following is NOT an Australian invention?",  "Bakelite", "Self-Propelled Rotary Hoe", "Kiwi Shoe Polish", "Two Stroke Lawn Mower"],
["Which horse won the 2009 Melbourne Cup?",  "Shocking", "Viewed", "Makybe Diva", "Ethereal"],
["In which Australian state or territory is Bundaberg?", "Queensland", "Tasmania", "Northern Territory", "South Australia"],
["Which of the following is NOT an Australian invention?",  "Tea bags", "Blast glass", "Vegemite", "Polymer bank notes"],
["Which Australian PM said 'Do you know why I have credibility? Because I don't exude morality'?",  "Bob Hawke", "John Gorton", "Joseph Lyons", "Robert Menzies"],
["Who is in the 'Guinness Book of Records' for sculling 2.5 pints of beer in 11 seconds?",  "Bob Hawke", "Alfred Deakin", "John Curtin", "Edmund Barton"],
["Which Australian PM was sacked by the Governor-General?",  "Gough Whitlam", "Billy Hughes", "Malcolm Fraser", "Alfred Deakin"],
["In which Australian state or territory is Katherine?", "Northern Territory", "Victoria", "Queensland", "Australian Capital Territory"],
["Which Australian band had a hit with 'Who made who'?", "AC/DC", "Jet", "Regurgitator", "INXS"],
["'Weary' Dunlop is a veteran of which war?", "WW2", "WW1", "Vietnam", "Iraq"],
["Which Australian actor starred in the movie 'Avatar'?", "Sam Worthington", "Mel Gibson", "Hugh Jackman", "Guy Pierce"],
["Which Australian musician sang 'Treat Yo Mama'?", "John Butler", "Rolf Harris", "Slim Dusty", "John Farnham"],
["Which Australian actor was once married to Tom Cruise?", "Nicole Kidman", "Cate Blanchett", "Kate Winslett", "Kylie Minogue"],
["Which Australian singer had a hit with 'Sadie'?", "John Farnham", "Michael Hutchence", "Angry Anderson", "Rolf Harris"],
["Which performer had a hit with 'Tie me kangaroo down, Sport'?", "Rolf Harris", "Angry Anderson", "Slim Dusty", "Peter Garrett"],
["Which Australian government minister was previously a rock musician?", "Peter Garrett", "Penny Wong", "Joe Hockey", "Morris Iemma"],
["With which war is the Hellfire Pass associated?", "WW2", "WW1", "Vietnam", "Iraq"],
["Which of the following is NOT an Australian invention?",  "Ethernet", "Google Wave", "Wireless LAN", "Google Maps"],
["Which words follow 'Australian's all, let us rejoice' in the national anthem?", "for we are young and free", "in golden soils", "in history's page", "advance Australia fair"],
["Which of the following is NOT an Australian invention?",  "Surfing", "Australian Crawl", "Calisthenics", "Polocrosse"],
["What is the nickname of the Collingwood Football Club?",  "Magpies", "Dragons", "Dockers", "Sharks"],
["What course of action is recommended after issuing of a Catastrophic Fire Warning?",  "Evacuate before any fires start", "Wait to hear if any fires start & then evacuate", "Stay & defend your property", "Wait for fire service to evacuate you"],
["The Australian national anthem is?", "Advance Australia Fair", "Waltzing Matilda", "God Save the Queen", "Down Under"],
["In Australian Football rules, how many players are allowed to be on the field at any one time?",  "18", "22", "16", "8"],
["What long-running Australian soap opera starred Kylie Minogue?", "Neighbours", "East Enders", "The Sullivans", "Coronation Street"],
["Where is the Australians of the Year Walk?",  "Canberra", "Sydney", "Perth", "Melbourne"],
["Which Australian cricketer was the subject of an Australian musical?",  "Shane Warne", "Rod Marsh", "Don Bradman", "Dennis Lillee"],
["What was Australian Don Bradman's career batting average?",  "99.94", "99.5", "88", "100 "],
["How many Australians were killed in the 2002 Bali bombings?",  "88", "18", "108", "100"],
["Which form of music is trumpeter James Morrison known for?",  "Jazz", "Opera", "Orchestral", "Rock"],
["How many teams compete in the Australian Football League?",  "16", "8", "20", "15"],
["What is Australian mainland's easternmost point?", "Byron Bay, New South Wales", "Cape Leeuwin, Western Australia", "Lord Howe Island", "Ballina New South Wales"],
["Which Australian singer is known as 'The Singing Budgie?'", "Kylie Minogue", "Marcia Hines", "Tina Arena", "Little Pattie"],
["Which Australian PM abolished tertiary education fees?",  "Gough Whitlam", "Robert Menzies", "Paul Keating", "Bob Hawke"],
["Which Australian singer starred in the original movie 'Grease'?",  "Olivia Newton John", "Little Pattie", "Wendy Matthews", "Edna Everage"],
["Which Australian is known for restoring sight around the world?", "Fred Hollows", "Victor Chang", "Dr Suess", "James Cook"],
["In which year did the war in Iraq begin?",  "2003", "2004", "2001", "1988"],
["Which colour is on the top half of the Aboriginal Flag (behind the sun)?",  "Black", "Red", "Yellow", "Green"],
["What date is Anzac Day?", "April 25th", "April 26th", "January 26th", "December 25th"],
["Which sport is known colloquially as 'Aerial Ping Pong'?", "Australian Rules Football", "Ruby League Football", "Table Tennis", "Sky Diving"],
["To what are Australian's referring by the term 'ankle biter'?", "Child", "Snake", "Possum", "Red Back Spider"],
["Which of the following are ingredients in Anzac biscuits?", "Rolled Oats & Golden Syrup", "Coconut & Vanilla", "Eucalyptus & Weet-Bix", "Sheep's Milk & Honey"],
["What was the name of the ship commanded by Lieutenant James Cook on his 1770 voyage to Australia?", "HMS Endeavour", "HMS Plymouth", "HMS Pandora", "HMS Queen Mary"],
["What is the alternate name for The Southern Cross?", "Crux", "Diamond", "Box", "Kite"],
["What is Australia's second most populous city?", "Melbourne", "Adelaide", "Brisbane", "Perth"],
["How long is the Mount Panorama circuit?",  "6.213 km", "6213 km", "62.13 km", "500 km"],
["What is Australia's third most populous city?", "Brisbane", "Adelaide", "Canberra", "Perth"],
["Approximately what percentage of Australians have Convict heritage?", "20% or more", "Under 5%", "5-10%", "10-15%"],
["In which year was gold first (officially) discovered in Australia?", "1851", "1876", "1900", "1800"],
["In which town or city is The Big Banana?",  "Coffs Harbour, New South Wales", "Byron Bay, New South Wales", "Rockhampton, Queensland", "Port Pirie, South Australia"],
["What is Australia's fourth most populous city?", "Perth", "Adelaide", "Hobart", "Canberra"],
["What is the capital of South Australia?", "Adelaide", "Whyalla", "Kingston", "Melbourne"],
["What is Australia's fifth most populous city?", "Adelaide", "Darwin", "Hobart", "Perth"],
["Which town is closest to Dangar Falls?",  "Dorrigo, New South Wales", "Armidale, New South Wales", "Appollo Bay, Victoria", "Derwent, Tasmania"],
["What is the capital of the Australian Capital Territory?", "Canberra", "Sydney", "Brisbane", "Melbourne"],
["During which period was Australia most severely affected by The Great Depression?", "1929-1932", "1913-1915", "1945-1949", "1917-1918"],
["Which of the following is NOT an Australian invention?", "Atmometer", "Black Box Flight Recorder", "Wine Cask", "Dynamic Lifter Fertiliser"],
["Who captained the HMS Endeavour?", "Cook", "Banks", "Bray", "Phillips"],
["Who founded Clean Up Australia?", "Ian Kiernan", "Norm Gallagher", "Dawn Fraser", "Ian Thorpe"],
["Which is Australia's largest state?",  "Western Australia", "Queensland", "Northern Territory", "South Australia"],
["Approximately what percentage of Australians have Aboriginal/Torres Strait Islander heritage?", "Under 3%", "12%", "20%", "5%"],
["Which of the following was NOT invented by an Australian?", "Air Conditioning", "Kerosene Refrigerator", "Stump Jump Plough", "The Box Kite"],
["Which politician's nickname is 'Ironbar'?", "Wilson Tuckey", "Joh Bjelke-Petersen", "Pauline Hanson", "Bob Hawke"],
["In what decade was decimal currency introduced to Australia?", "1960's", "1970's", "1940's", "1930's"],
["What is the name of the Victorian Cricket Australia team?",  "Bushrangers", "Rangers", "Bulldogs", "Wallabies"],
["What is Australia's largest export industry?", "Coal", "Tertiary Education", "Wheat", "Rare Earth Metals"],
["What often replaced money in financial transactions in early Australian colonial life?", "Rum", "Gold", "Favours", "Flour"],
["Which industry is Australia's largest CO₂ emitter?",  "Coal powered electricity", "Agriculture", "Transport", "Bushfires"],
["What is Australia's northernmost mainland point?",  "Cape York, Queensland", "Darwin, Northern Territory", "Broom, Western Australia", "Melbourne, Victoria"],
["What percentage best fits Australia's contribution to global greenhouse gas emissions?",  "Under 2%", "Between 2-5%", "Between 10-15%", "Over 15%"],
["In which year did Wild Oats XI make history by winning four consecutive Sydney to Hobarts?", "2008", "2006", "2007", "2009"],
["Which religious group started the Sanitarium Health Food Company?", "Seventh-Day Adventists", "Marmites", "Mormons", "Catholics"],
["In what year was the Australian 2 dollar coin introduced?", "1988", "1984", "1978", "2000"],
["In which Australian state or territory is Launceston?", "Tasmania", "Victoria", "Northern Territory", "Australian Capital Territory"],
["In what year did Australia hold a referendum on becoming a republic?", "1999", "1988", "2000", "2001"],
["Which industry sector constitutes almost 70 per cent of Australia's GDP?", "Services", "Agriculture", "Mining", "Finance"],
["In what year was the Australian dollar floated?", "1983", "1978", "1986", "1966"],
["Which of the following poets wrote Waltzing Matilda?", "Banjo Patterson", "Judith Wright", "Henry Lawson", "Kath Walker"],
["Which of the following poems is NOT written by Banjo Patterson?", "Blood & Bone", "Clancy of the Overflow", "Waltzing Matilda", "The Man from Snowy River"],                 
["What is the name for Echidna young?", "Puggles", "Wiggles", "Pups", "Poogles"],
["Off which Australian coast is Kangaroo Island?", "South Australia", "Victoria", "Western Australia", "Queensland"],
["Which political event led to a split in the Australian Labor Party over communism?", "The Petrov Affair", "The Great Depression", "The Vietnam War", "WWII", "The Hilton bombing"],
["Which Australian author wrote The Cabbage Patch Fib?", "Paul Jennings", "Graeme Base", "Catherine Jinks", "Jack Bedson"],
["Who is Commander-in-Chief of the Australian Defence Force?", "Governor-General", "Queen Elizabeth II",  "Minister for Defence", "Prime Minister"],
["Where did the Mister Squiggle character live?", "The Moon", "Saturn", "Mars", "Australia"],
["How many seven pointed stars are there on the Australian Flag?", "5", "1", "4", "6"],
["In what year did Australia win The America's Cup?", "1983", "1987", "1938", "2003"],
["Which union stopped the Royal Botanic Gardens from being turned into a car park for the Sydney Opera House?", "BLF", "AMEU", "AEU", "APSU"], 
["Which of the following facts are NOT true of Dick Smith?",  "He crossed the Coral Sea by balloon", "Hoaxed Australian media into thinking he had towed an iceberg from Antarctica to Sydney Harbour", "Named his line of Australian made matches 'Dickheads'", "Found the Kookaburra which crashed in the Central Desert in 1929"],
["What is the name for Echidna young?", "Puggles", "Wiggles", "Pups", "Poogles"],
["Where does the Echidna get its name?", "Greek mythological name meaning 'The Mother of all Monsters'", "An Aboriginal dialect", "Captain Cook", "Latin", "Abel Tasman"],
["In which Australian capital is there an outdoor staircase shaped like DNA?", "Perth", "Sydney", "Melbourne", "Adelaide"],
["When was the word Australia officially adopted by the Admiralty?", "1824", "1898", "1901", "1788"],
["In which year did the United Kingdom officially claim the western part of Australia?", "1829", "1729", "1898", "1877"],
["In what year was the Northern Territory founded as a separate territory?", "1911", "1989", "1901", "1899"], 
["From which state or territory was the Northern Territory excised in 1911?", "SA", "WA", "QLD", "VIC"],
["Which court case overturned the notion of 'terra nullius'?", "Mabo v Queensland (No2)", "Wik", "Chapman v Luminis Pty Ltd", "Chapman v Waters"],
["For what is Arnhem Land named?", "Named for the Dutch ship which explored the coast in 1623", "Named by local indigenous people", "Named by explorer Robert Burke", "Named after the wife of local missionary"],
["From which language is the word Australia derived?", "Latin", "Eora", "Dutch", "French"],
["What was Peter James Knight protesting when he killed a Melbourne security guard in 1954?", "Abortion", "Vietnam War", "Communism", "Capitalism"],
["When was the Sanitarium Health Food Company originally formed?", "1898", "1968", "1934", "1972"],
["Which religious group started the Sanitarium Health Food Company?", "Seventh-Day Adventist", "Marmites", "Mormons", "Catholics"],
["How many cricketers have been Australian of the Year?", "3", "1", "4", "2", "0"],
["Who is the only artist to have been Australian of the year?", "Arthur Boyd", "Pro Hart", "William Dobell", "Ken Done"],
["Who was the first Australian to be knighted for services to music?", "Bernard Heinze", "Slim Dusty", "Joan Sutherland", "Judith Durham"],
["In which year was the Australian of the Year first awarded?", "1960", "1970", "1950", "1945"],
["How many species of Goanna are found in Australia?", "25", "30", "22", "19"],
["Which of the following is NOT true of Rolf Harris?", "He taught in Perth primary schools", "He performed the opening show of the Sydney Opera House", "He invented the 'wobble board'", "He worked with the Beatles"],
["Which Australian magazine is publicly cited as having been an initiative of a CIA front group?", "Quadrant", "The Bulletin", "The Womens Weekly", "Zoo Weekly"],
["Which Australian magazine was the subject of a 2009 scientific hoax?", "Quadrant", "The Bulletin", "National Geographic", "Australian Journal of Crop Science"],
["Which Australian magazine offered an all-expenses divorce as a competition prize?", "Zoo Weekly", "Dolly", "Cleo", "Ralph"],
["Which of the following jobs was NOT one held by Banjo Patterson", "Trawlerman", "Lawyer", "Jockey", "Soldier"],
["What was the Sydney Push?", "Left wing intellectual subculture based in Sydney pubs", "Colloquialism for peak hour in Sydney", "A swimming stoke invented by Bondi life-savers", "A non-motorised tram used on Sydney railways"],
["Which item of clothing, found 2 years after the imprisonment of Lindy Chamberlain, secured her release?", "Matinee jacket", "Bonnet", "Nappy", "Singlet"],
["Which trial was dubbed the 'Trial of the Century'?", "(Lindy) Chamberlain  v R", "Mabo v Queensland", "ASIC proceedings against James Hardie Pty Ltd", "Haneef v Minister for Immigration & Citizenship"],
["Which of the following poets wrote Waltzing Matilda?", "Banjo Patterson", "Judith Wright", "Henry Lawson", "Kath Walker"],
["Which of the following poems is NOT written by Banjo Patterson?", "Blood & Bone", "Clancy of the Overflow", "Waltzing Matilda", "The Man from Snowy River"],
["Which of the following is TRUE of goannas?", "No species of goanna of their species can swim", "Goannas can not climb trees", "Goannas are herbivores", "Goannas are nocturnal"],
["Which of the following is NOT a species of Kangaroo?", "Southern Brown Kangaroo", "Antilopine Kangaroo", "Eastern Grey Kangaroo", "Western Grey Kangaroo"],
["With which war is the Kokoda Track associated?", "WW2", "WW1", "Vietnam", "Boer War"],
["Which of the following facts is NOT true of the Kangaroo?", "Kangaroos can not swim", "It is the largest surviving marsupial in the world", "They release virtually no methane", "From the family Macropodidae"],
["Which colour is on the bottom of the Aboriginal Flag (behind the sun)?", "Red", "Black", "White", "Yellow"],
["Which Act removed the right of the UK parliament to change the Australian Constitution?", "The Australia Act", "Judiciary Act 1903", "Border Protection Act", "Royal Powers Act 1953"],
["In 1856 which group downed tools & marched successfully to introduce the 8 hour day?", "Stonemasons", "Shearers", "Wharfies", "Builders Labourers"],
["What was Captain Moonlight's real name?", "Andrew George Scott", "Ben Hall", "Edward Kelly", "Thomas Charles Wyndham"],
["Who was the first Australian woman to win an Olympic gold medal in a swimming event?", "Fanny Durack", "Mina Wylie", "Shane Gould", "Claire Dennis"],
["Which Australian jurisdiction has NOT participated in harmonisation of Criminal Codes?", "TAS", "Commonwealth", "ACT", "NT"],
["Which of the following Australian states/territories is NOT among the Common Law jurisdictions?", "WA", "NSW", "SA", "VIC"],
["Which Australian was known as Australia's Leonardo?", "David Unaipon", "Lance Hill", "Lawrence Hargrave", "Sally Dominguez"],
["What is the name of the Victorian Cricket Australia team?",  "Bushrangers", "Rangers", "Bulldogs", "Wallabies"],
["Which was the first Australian newspaper to include political cartoons?", "Cornwall Chronicle", "The Sydney Morning Herald", "The Australian", "The Bulletin"],
["Which political party introduced the WorkChoices Legislation?", "The Liberal Party of Australia", "Australian Labor Party", "The Greens", "The Democrats"],
["In which year was the inaugural Sydney to Hobart Yacht Race held?", "1945", "1937", "1956", "1978"],
["During which year did five yachts sink during the Sydney to Hobart Yacht Race?", "1998", "1978", "1995", "1989"],
["In which year did Wild Oats XI make history by winning four consecutive Sydney to Hobarts?", "2008", "2006", "2007", "2009"],
["Who is known as 'The Black Ned Kelly'?", "Jandamarra", "Cameron Doomadge",  "Lex Wotton", "Jeremy Geia"],
["How many wickets were taken by Ian Bothem in his career?", "383", "248", "127", "504"],
["During which period was Australia most severely affected by The Great Depression?", "1929-1932", "1913-1915", "1945-1949", "1917-1918"],
["Which politician was NOT President of the Australian Council of Trade Unions?", "Greg Combet", "Bob Hawke", "Simon Crean", "Jenny George"],
["Which of the following is NOT an objective of the Australian Council of Trade Unions Constitution?", "Increased migration", "The socialisation of industry", "Full employment", "Organisation of trade & salary earners"],
["What was the name of the BLF's radio program on Radio 3CR?", "The Concrete Gang", "Where Angels Fear to Tread", "Dare to Struggle", "Up Their Cazaly"],
["Which of the following is NOT true of Roy Cazaly?", "He won the Brownlow Medal 3 times", "A song was named after him", "He never won the Brownlow Medal", "He could kick a football over 65m"],
["How many Australians were among the 'Balibo Five'?", "2", "5", "1", "4"],
["What was the Springbok Tour of 71?", "A controversial tour of Australia & NZ by South African rugby team", "Australian tour of US folk band", "Pre-election promotional tour by QLD politician", "1971 tour of South Africa which ended in bus crash"],
["What is the circumference of Uluru?", "9.4 km", "10 km", "19 km", "6.7 km"],
["What was the name of the only successful armed takeover of the Australian government? ", "The Rum Rebellion", "The Eureka Stockade", "The Castle Hill Rebellion", "WW2"],
["Which Australian PM changed parties five times?", "Billy Hughes", "Bob Hawke", "Harold Holt", "Malcolm Fraser"],
["What is on the Eureka Flag?", "White cross overlaid with Southern Cross on blue background", "Union Jack", "Hammer & Sickle", "Red, white & blue stripes overlaid with Southern Cross"],
["Which 1891 QLD event threatened to erupt into civil war? ", "The Shearers Strike", "The QLD Meat Strike", "The Rum Rebellion", "Castle Hill Rebellion"],
["In what decade was decimal currency introduced to Australia?", "1960's", "1970's", "1940's", "1930's"],
["What is Australia's largest export industry?", "Coal", "Tertiary Education", "Wheat", "Rare Earth Metals"],
["What often replaced money in financial transactions in early Australian colonial life?", "Rum", "Gold", "Favours", "Flour"],
["How many years was the longest drought in Australia's recorded history?", "8", "3", "5", "6"],
["Who said, 'Cattle Kings ye call us, then we are Kings in grass castles that may be blown away upon a puff of wind'?", "Patrick Durack", "R M Williams", "Cheong Liew", "Rory O'Grady"],
["In what year did Australia's longest heat wave (in recorded history) occur?", "1923-1924", "2008-2009", "1938-1939", "2005-2006"],
["How many species of fauna are there in Australia?", "Between 600,000 & 700,000", "Between 6000 & 7000", "Between 600 & 700", "66-70"],
["Which of the following is NOT an Australian invention?", "Atmometer", "Black Box Flight Recorder", "Wine Cask", "Dynamic Lifter Fertiliser"],
["Which of the following was NOT invented by an Australian?", "Air Conditioning", "Kerosene Refrigerator", "Stump Jump Plough", "The Box Kite"],
["Which was the last Australian state or territory to abolish the death penalty? ", "NSW in 1985", "QLD in 1965", "VIC in 1938", "TAS in 1923"],
["Approximately what percentage of Australians have Convict heritage?", "20% or more", "Under 5%", "5-10%", "10-15%"],
["Approximately what percentage of Australians have Aboriginal/Torres Strait Islander heritage?", "Under 3%", "12%", "20%", "5%"],
["How many Aboriginal dialects existed in Australia prior to European arrival?", "Over 200", "Between 100-200", "Between 50-100", "Between 1-50"],
["What is Australian mainland's southernmost point?", "South Point, Wilsons Promontory, VIC", "Cape Leeuwin, WA", "Catamaran, TAS", "Cape Ottway, VIC"],
["What is Australian mainland's easternmost point?", "Byron Bay, NSW", "Cape Leeuwin, WA", "Lord Howe Island", "Ballina NSW"],

["What is Australian mainland's westernmost point?", "Steep Point, WA", "Cape Leeuwin, WA", "Broome, WA", "Margaret River, WA"],
["From which language was the word Canberra taken?", "Ngunnawal", "Pitjantjatjara", "Koori", "English"],
["Which Australian poet was criticised for sedition for his poem 'Freedom on the Wallaby'? ", "Henry Lawson", "Banjo Patterson", "Judith Wright", "Les Murray"],
["In what year did the Australian Citizenship Act receive Royal Assent?", "2007", "1901", "1967", "1937"],
["In which year was political suffrage extended to all non-Aboriginal Australian women?", "1902", "1856", "1901", "1898"],
["Which politician's nickname is 'Ironbar'?", "Wilson Tuckey", "Joh Bjelke-Petersen", "Pauline Hanson", "Bob Hawke"],
["In which year was gold first (officially) discovered in Australia?", "1851", "1876", "1900", "1800"],
["In what year did Australia's first stock exchange open?", "1861", "1900", "1961", "1934"],
["Of what type of rock is Uluru primarily composed?",  "Sandstone", "Granite", "Basalt", "Limestone"],
["In which town or city is The Big Banana?",  "Coffs Harbour, NSW", "Byron Bay, NSW", "Rockhampton, QLD", "Port Pirie, SA"],
["In which town or city is The Big Lobster?",  "Kingston, SA", "Port Augusta, SA", "Darwin, NT", "Wyndham, WA"],
["Which is Australia's largest state or territory?",  "WA", "QLD", "NT", "SA"],
["Which route is the Channel Country Run?",  "Port Augusta to Birdsville", "Perth to Adelaide", "Darwin to Brisbane", "Melbourne to Sydney"],
["Who said 'The greatest thing that could happen to the state & nation is when we get rid of all the media...'",  "Joh Bjelke-Petersen", "John Howard", "Wilson Tuckey", "Kyle Sandilands"],
["What is the current name for the town known by the local Aboriginals as Cavvanbah?",  "Byron Bay", "Kempsey", "Bowraville", "Tweed Heads"],
["In which state is the Whispering Wall?",  "SA", "VIC", "TAS", "WA"],
["In which Australian state or territory is the Shark Bay World Heritage Area?",  "WA", "SA", "NT", "TAS"],
["Off which Australian coast are the stromatolites found?",  "WA", "QLD", "NSW", "SA"],
["Which Australian state or territory was placed under military control after WW2?",  "NT", "QLD", "NSW", "ACT"],
["Near which town was Martial Law applied in 1824 to quell conflict between Aboriginals & settlers?",  "Bathurst", "Mt Isa", "Alice Springs", "Castle Hill"],
["Which war did the Coo-ee March recruit for? ",  "WW1", "WW2", "Vietnam War", "War on Terror"],
["Where did the Coo-ee March begin?",  "Gilgandra", "Warragul", "Sydney", "Melbourne"],
["In what year did WW2 begin?",  "1939", "1942", "1843", "1955"],
["In which year did the war in Iraq begin?",  "2003", "2004", "2001", "1988"],
["Which group rebelled in the Castle Hill Rebellion of 1804?",  "Irish convicts", "Aboriginals", "Chinese immigrants", "Torres Strait Islanders"],
["How many Australians were killed in the 2002 Bali bombings?",  "88", "18", "108", "100"],
["Which Australian PM established diplomatic relations with the People's Republic of China?",  "Gough Whitlam", "Kevin Rudd", "Paul Keating", "Joseph Lyons"],
["Which Australian PM called on Iraq for a US$500,000 campaign donation? ",  "Gough Whitlam", "John Curtin", "John Howard", "Paul Keating"],
["Which Australian PM abolished tertiary education fees?",  "Gough Whitlam", "Robert Menzies", "Paul Keating", "Bob Hawke"],
["Which political party reintroduced fees for tertiary education in the late 80's?",  "The Australian Labor Party", "Liberal Party of Australia", "The Country Party", "The White Australia Party"],
["Which Australian PM was thought to have supported Indonesia's occupation of East Timor?",  "Gough Whitlam", "John Howard", "Kevin Rudd", "Malcolm Fraser"],
["What was the first international treaty signed by Australia?",  "Treaty of Versailles", "International Covenant on Civil & Political Rights", "Covenant on the Abolition of the Death Penalty", "The Federation Treaty"],
["Who founded the Liberal Party of Australia?",  "Robert Menzies", "Alfred Deakin", "Joseph Lyons", "Edmund Barton"],
["Which Australian PM is attributed the quote 'All the way with LBJ'? ",  "Harold Holt", "John McEwan", "John Gorton", "Gough Whitlam"],
["Which Australian singer is known as 'The Singing Budgie?'", "Kylie Minogue", "Marcia Hines", "Tina Arena", "Little Pattie"],
["Which Australian singer starred in the original movie 'Grease'?",  "Olivia Newton John", "Little Pattie", "Wendy Matthews", "Edna Everage"],
["Which Australian soprano was born Helen Porter Mitchell?",  "Nellie Melba", "Edna Everage", "Joan Sutherland", "Kiri Te Kanawa"],
["Which form of music is trumpeter James Morrison known for?",  "Jazz", "Opera", "Orchestral", "Rock"],
["Which Rap band hails from Adelaide SA?",  "Hilltop Hoods", "Koolism", "Bliss n Eso", "AC/DC"],
["Which Australian band won the 1983 United Nations Media Peace Prize?",  "Midnight Oil", "AC/DC", "Cold Chisel", "The Angels"],
["Which Australian singer replaced Glen Shorrock as lead singer of Little River Band during the 80's?",  "John Farnham", "Jimmy Barnes", "Peter Garrett", "Michael Hutchence"],
["Where is The Pub with no Beer?",  "Taylors Arm, NSW", "Alice Springs, NT", "Mt Isa, QLD", "Oodnadatta, SA"],
["What is Australia's longest running television show?",  "Four Corners", "Hey Hey its Saturday", "Neighbours", "Sesame Street"],
["Which Australian country singer sang 'The Pub with no Beer'?",  "Slim Dusty", "Shannon Noll", "Smoky Dawson", "Col Joye"],
["Which Olympian was almost sent home from the 1994 Commonwealth Games for an incident involving a fire-arm?",  "Kieren Perkins", "Grant Hackett", "Ian Thorpe", "John Davies"],
["Who was the first Aboriginal woman to win Olympic gold?",  "Nova Peris-Kneebone", "Cathy Freeman", "Evonne Goolagong", "Rohanee Cox"],
["Who is the first female swimmer ever to win three Olympic gold medals in world record time?",  "Shane Gould", "Ian Thorpe", "Linda Mackenzie", "Bonnie Mealing"],
["Which Australian runner broke the 4-minute-mile over 17 times?",  "Herb Elliott", "Robert De Castella", "Cathy Freeman", "Pat Farmer"],
["Who lit the cauldron at the 2000 Sydney Olympics?",  "Cathy Freeman", "John Howard", "Ian Thorpe", "Pauline Hanson"],
["What was Australian Don Bradman's career batting average?",  "99.94", "99.5", "88", "100 "],
["What was the name of the set of bowling tactics devised by England to deal with Don Bradman?",  "Bodyline", "Hook, line & sinker", "Hat Trick", "Ashes to Ashes"],
["When did The Ashes cricket series begin?",  "1882", "1800", "1904", "1963"],
["When was the first cricket Test match between Australia & England?",  "1876-1877", "1882-1883", "1904-1905", "1963-1964"],
["In which Australian city is the Australian Formula One Grand Prix held annually?",  "Melbourne", "Adelaide", "Brisbane", "Hobart"],
["How long is the Mount Panorama circuit?",  "6.213 km", "6213 km", "62.13 km", "500 km"],
["How many teams compete in the Australian Football League?",  "16", "8", "20", "15"],
["Which was the first Australian Football League club?",  "Melbourne Football Club", "Sydney Football Club", "Collingwood Football Club", "Carlton Football Club"],
["What is the nickname of the Collingwood Football Club?",  "Magpies", "Dragons", "Dockers", "Sharks"],
["In Australian Football rules, how many players are allowed to be on the field at any one time?",  "18", "22", "16", "8"],
["Where is the Australians of the Year Walk?",  "Canberra", "Sydney", "Perth", "Melbourne"],
["Which Australian cricketer was the subject of an Australian musical?",  "Shane Warne", "Rod Marsh", "Don Bradman", "Dennis Lillee"],
["What is the name of the Chinese-Australian whose life story is told in 'Mao's Last Dancer'?",  "Li Cunxin", "Tommy Lee", "Chi Cao", "Chengwu Guo"],
["What was the name of the Australia's first WW2 prisoner of war?",  "Hajimi Toyoshima", "Li Cunxin", "Yamada Taramu", "Cho Suzuki"],
["Who captured the first WW2 prisoner of war taken on Australian territory?",  "Tiwi Islanders", "Australian armed forces", "Indonesian civilians", "US troops"],
["How many Japanese died in the Cowra breakout?",  "231", "24", "4", "2400"],
["In what year was the Spanish Flu epidemic?",  "1918-1919", "1922-1923", "1854-1856", "1966-1967"],
["How many died on the Australian mainland during the Spanish Flu pandemic?",  "At least 12,000", "Between 1000-2000", "Between 2000-8000", "Between 8000-10000"],
["How many people died in the Black Saturday bushfires of 2009?",  "173", "71", "243", "54"],
["What was the password used by the rebels at the Eureka Stockade?",  "Vinegar Hill", "Fish n Chips", "Eureka", "Blue Moon"],
["Which Australian PM was awarded the US Medal of Freedom?",  "John Howard", "Kevin Rudd", "Robert Menzies", "William McMahon"],
["Which Australian PM said 'Two blokes with moustaches & a spaniel do not make a family'?",  "Paul Keating", "John Howard", "Kevin Rudd", "Robert Menzies"],
["Which Australian PM repealed the ban on gay & lesbians serving in the armed forces?", "Paul Keating", "Kevin Rudd", "Billy Hughes", "John Howard"],
["Which gay activist High Court judge became known as 'The Great Dissenter'?",  "Michael Kirby", "Isaac Isaacs", "Murray Gleeson", "Lionel Keith Murphy"],
["Which Australian PM said 'Do you know why I have credibility? Because I don't exude morality'?",  "Bob Hawke", "John Gorton", "Joseph Lyons", "Robert Menzies"],
["Who is in the 'Guinness Book of Records' for sculling 2.5 pints of beer in 11 seconds?",  "Bob Hawke", "Alfred Deakin", "John Curtin", "Edmund Barton"],
["Which Australian PM was sacked by the Governor-General?",  "Gough Whitlam", "Billy Hughes", "Malcolm Fraser", "Alfred Deakin"],
["Who was Australia's first female Nobel Prize winner?",  "Elizabeth Blackburn", "Mary May Williams", "Karyn Josephs", "Amelia Fitzgerald"],
["Which is the highest mountain on the Australian mainland?", "Mount Kosciuszko", "Cradle Mountain", "Big Ben", "Mawson Peak"],
["How big is the SkyMapper telescope?", "1.35m", "1.0m", "2.4m", "0.90m"],
["From which Australian movie is the quote, 'Tell him he's dreaming'?", "The Castle", "Samson & Delilah", "Crocodile Dundee", "Kenny"],
["From which Australian movie is the quote, 'That's not a knife...THIS is a knife'?", "Crocodile Dundee", "My Tehran for Sale", "Australia", "Romper Stomper"],
["What is the approximate distance from Earth to the South Star?", "270 light years", "30 light years", "204 light years", "17 light years"],
["What is the approximate distance from Earth to the South Star?", "430 light years", "307 light years", "270 light years", "172 light years"],
["Which of the following is NOT a star in the Southern Cross?",  "Sirius", "Acrux", "Mimosa", "Delta Crucis"],
["Graeme Clark is responsible for pioneering research into which of the following?",  "Bionic Ear", "Bionic Eye", "Bionic Hand", "Bionic Leg"],
["In which Australian state or territory is Wave Hill?",  "NT", "WA", "SA", "QLD"],
["Which Australian was a member of the New Zealand Communist Party?",  "Fred Hollows", "Ned Kelly", "Dick Smith", "Pro Hart"],
["Which Australian PM was also known as 'Pig-iron Bob'?",  "Robert Menzies", "Bob Hawke", "Ben Chifley", "Billy Hughes"],
["Which of the following facts are NOT true of Dick Smith?",  "He crossed the Coral Sea by balloon", "Hoaxed Australian media into thinking he had towed an iceberg from Antarctica to Sydney Harbour", "Named his line of Australian made matches 'Dickheads'", "Found the Kookaburra which crashed in the Central Desert in 1929"],
["Who was the first Aboriginal to be made an Australian Citizen?",  "Albert Namatjira", "Mum Shirl", "Oodgeroo Nooncal", "Bennelong"],
["Which Australian artist was against gun control?",  "Pro Hart", "Arthur Streeton", "Tom Roberts", "Brett Whiteley"],
["Which Australian artist created 'The American Dream'?",  "Brett Whiteley", "Pro Hart", "Sidney Nolan", "Ken Done"],
["The development of which architectural icon was famously dubbed 'Malice in Blunderland'?",  "Sydney Opera House", "Sydney Harbour Bridge", "Olympic Dam", "Olympic Stadium"],
["In what year were the Olympics in Melbourne?",  "1956", "2000", "1960", "1954"],
["In what year was Chateau Tanunda built?",  "1890", "1980", "1800", "1899"],
["In what year was the Australian National Route Numbering System introduced?",  "1955", "1945", "1965", "1975"],
["What is the name of the highway from Canberra to Yarra?",  "Federal Highway", "Hume Highway", "Castlereagh Highway", "Barton Highway"],
["What is the name of the highway from Camooweal, QLD to Tenant Creek, NT?",  "Barkly Highway", "Warrego Highway", "Stuart Highway", "Sturt Highway"],
["In which Australian state or territory is the Walls of Jerusalem National Park?",  "TAS", "WA", "NT", "KI"],
["What was the original name of Brisbane's Story Bridge?",  "Jubilee Bridge", "Federation Bridge", "The Arch", "Swanport Bridge"],
["Which Aboriginal people objected to the building of the Hindmarsh Island Bridge?",  "Ngarrindjeri", "Arakwal", "Yinguo", "Eneewin"],
["During the last century how many children received care in Australian orphanages?",  "Over 500,000", "300,000-500,000", "203,459", "150,000"],
["Which industry is Australia's largest CO₂ emitter?",  "Coal powered electricity", "Agriculture", "Transport", "Bushfires"],
["What is Australia's northernmost mainland point?",  "Cape York, QLD", "Darwin, QLD", "Torres Strait", "Cape Leeuwin, QLD"],
["What percentage best fits Australia's contribution to global greenhouse gas emissions?",  "Under 2%", "Between 2-5%", "Between 10-15%", "Over 15%"],
["Australia's stimulus package for the GFC constituted what percentage of our GDP?",  "4%", "6%", "10%", "1.7%"],
["What is the maximum permitted blood alcohol level for (full licence) driving in Australia?",  "0.05%", "0.5%", "0.08%", "0.8%"],
["Which Australian PM has been described 'the principal architect' in the rise of Robert Mugabe?",  "Malcolm Fraser", "Paul Keating", "Gough Whitlam", "Kevin Rudd"],
["What is the title of the first indigenous Australian opera?",  "Pecan Summer", "Rites", "Bran Nue Day", "Yanagai! Yanagai!"],
["What event is said to have sparked the 2005 Cronulla race Riots?",  "A scuffle between lifesavers &  Lebanese-Australians", "Serbian v Bosnian football match", "21st party advertised on Facebook", "Ongoing tensions between indigenous locals & the police"],
["Which Australian radio shock-jock did ACMA find to have 'encouraged violence' in the lead up to the riots?",  "Alan Jones", "Kyle Sandilands", "John Laws", "Derryn Hinch"],
["What is the name of the Panda Bears now resident in Adelaide Zoo?",  "Wang Wang & Funi", "Shoni & Gogou", "Yogi & Big Ted", "Samune & Nee Nee"],
["Who was involved in the riot known as the 'Battle of Brisbane'?",  "Australian v US service personnel", "Local indigenous peoples & settlers", "Immigrants & squatters", "White settlers & European immigrants"],
["Which indigenous Australians live on Melville Island?",  "Tiwi", "Koorie", "Murri", "Palawa"],
["Which indigenous Australians were the original inhabitants of Arnhem Land?",  "Yolgnu", "Wangkai", "Noongar", "Yamatji"],
["Which Australian anthropologist wrote 'Nomads of the Australian Desert'?",  "Charles Mountford", "George Bass", "Robert Burke", "Matthew Flinders"],
["In what year was 'The Bulletin' magazine originally published?",  "1880", "1876", "1886", "1890"],
["Which slogan is associated with defunct magazine 'The Bulletin'?",  "Australia for the White Man", "Australia for All", "Business as Usual", "Australia for the Commonwealth"],
["Which political movement was linked to the Eureka Stockade?",  "Chartism", "Communism", "Fascism", "Colonisation"],
["Where was the miner's oath sworn leading up to the Eureka Stockade?",  "Bakery Hill", "Vinegar Hill", "Castle Hill", "Stock Yard Hill"],
["In which year was the Australia Act passed?",  "1986", "1896", "1901", "2006"],
["Which political party brought in the Goods & Services Tax?",  "Liberal Party of Australia", "Australian Labor Party", "National Party of Australia", "Family First"],
["Which Australian state or territory first gave women the vote?",  "SA", "VIC", "NSW", "ACT"],
["What sections of the Constitution are used to defend Darryl Kerrigan's home against compulsory acquisition in 'The Castle'?", "51 & 109", "106 & 120", "71 & 98", "2 & 66"], 
["Which section of The Australian Constitution was repealed in 1967?", "127", "4", "38", "39"],
["In which year did Australian Federal politics gain its first female representative?",  "1943", "1898", "1962", "1955"],
["Which political event precipitated the introduction of the arbitration system for industrial disputes?",  "1890 Maritime Dispute", "1854 Eureka Stockade", "1899 Freemantle Lumpers Strike", "1985 Victorian Nurses Strike"],
["In what year were polymer notes introduced?",  "1988", "1989", "1898", "1967"],
["Which Australian state was the first source of economic mining?",  "SA", "WA", "NT", "VIC"],
["How many days was Australia's longest heat wave?",  "160", "16", "63", "174"],
["Which town recorded Australia's highest temperature?",  "Oodnadatta, SA", "Wyndham, WA", "Marble Bar, WA", "Mardie, WA"],
["Which farming method was invented by an Australian?",  "Permaculture", "Slash & burn", "No-till farming", "Strip-till"],
["From which language is the name Nullarbor taken?",  "Latin", "Wangai", "English", "Ngaanyatjarra"],
["How many sections does The Australian Constitution have?", "128", "50", "100", "98"],
["What was the topic of the McClelland Royal Commission?",  "Effects of nuclear tests in central Australia", "Aboriginal deaths in custody", "The collapse of HIH", "The Victorian bushfires"],
["In the Australian context, what was Operation Buffalo?",  "Nuclear testing program in central Australia", "Police investigation following the Cronulla riots", "The ASIO plan to assassinate Harold Holt", "ASIO investigation into Muslim extremists"],
["Which of the following is NOT the codename for an Operation Antler test?", "Knuckle", "Kite", "Marcoo", "Breakaway"],
["Which of the following is NOT the name of a test of triggering mechanisms of nuclear bombs performed at Maralinga?", "Kamilaroi", "Tadje", "Biak", "Taranaki"],
["Which year saw Australia's largest settlement of immigrants since WW2?",  "1969-1970", "1989-1990", "2002-2003", "2008-2009"],
["Which of the following Aboriginal languages means Earth, Dirt, Ground, Land?",  "Pitjantjatjara", "Bunuba", "Nhirrpi", "Koorie"],
["In which Australian state or territory is Mamungkukumpurangkuntjunya Hill?",  "SA", "WA", "NT", "TAS"],
["Who coined the phrase 'black armband view of history'?",  "Geoffrey Blainey", "Andrew Bolt", "Miranda Devine", "Andrew Denton"],
["On which date did Kevin Rudd & Brendan Nelson deliver the official apology to indigenous Australia?",  "13 February 2008", "12 February 2008", "13 March 2008", "14 February 2008"],
["Which Australian PM said 'its no good crying over spilt milk, all you can do is bail up another cow'?",  "Joseph Chifley", "Ben Chifley", "John Gorton", "John Howard"],
["What species did Steve Irwin discover a new strain of?",  "Turtle", "Crocodile", "Lizard", "Snail"],
["What is the name of the Australian air-breathing land snail that was named after Steve Irwin?",  "Crikey steveirwini", "Amber crocodile Hunter", "Banded white-lipped", "Helicaron Irwini"],
["In which space shuttle was Andy Thomas' first trip to space?",  "Endeavour", "Discovery", "Challenger", "Columbia"],
["Which horse holds the record for The Melbourne Cup?",  "Kingston Rule", "Phar Lap", "Rain Lover", "Empire Rose"],
["Which part of Phar Lap's anatomy is displayed at the National Museum of Australia?",  "Heart", "Hide", "Skeleton", "Mane & tail"],
["In what year did Phar Lap win The Melbourne Cup?",  "1930", "1928", "1968", "1942"],
["Which horse won the 2009 Melbourne Cup?",  "Shocking", "Viewed", "Makybe Diva", "Ethereal"],
["In what year was a show-case State of Origin match played in California?",  "1987", "1977", "2007", "1985"],
["Which former Australian rugby league player has the nickname 'The King'?",  "Wally Lewis", "Wendell Sailor", "Jarryd Hayne", "Anthony Mundine"],
["Which Australian netball team have won 9 of the 12 Netball World Championships?",  "Diamonds", "QLD Fusion", "Canberra Darters", "AIS"],
["Approximately how much does each Australian Olympic medal cost in funding terms?",  "$15 million", "$5 million", "$29 million", "$7,596"],
["Which golfer was nicknamed 'The Great White Shark'?",  "Greg Norman", "Tiger Woods", "Ian Baker-Finch", "Brett Ogle"],
["What is the oldest active sports trophy won by Australia?",  "The Americas Cup", "The Ashes", "ICC Champions Trophy", "Melbourne Cup"],
["Who was the first woman to swim 100m in less than 60 seconds?",  "Dawn Fraser", "Shane Gould", "Susie O'Neill", "Stephanie Rice"],
["From which Aboriginal people is Wimbledon champion Evonne Goolagong Cawley?",  "Wiradjuri", "Koorie", "Murrie", "Anangu"],
["In which year did Evonne Goolagong become the first indigenous Australian to win Wimbledon?",  "1971", "1961", "1951", "1981"],
["Which of the following fauna is a native Australian species?",  "Rabbit-eared Bandicoot", "Camel", "Goat", "Cane Toad"],
["Which species of bird was introduced to manage locust plagues?",  "Indian Mynah", "Common Starling", "Rock Pigeon", "Sparrow"],
["Which of the following is a native Australian marine species?",  "Trout Cod", "Carp", "Brown Trout", "Rainbow Trout"],
["Hostility between which two Australian unions stopped the formation of 'One Big Union'?", "WIUA & AWU", "CFMEU & BLF", "AEU & PSU", "NSWTF & AEU"],
["Which marine species has devastated parts of the Great Barrier Reef?",  "Crown-of-Thorns Starfish", "New Zealand Green-Lipped Mussel", "European Shore Crab", "Black-Striped Mussel"],
["How was the Cane Toad introduced to Australia?",  "Deliberately introduced to control the Cane Beetle", "Accidentally introduced through shipping", "Escaped from a laboratory", "Deliberately introduced as pets"],
["Which of the following Emu facts is false?",  "The Emu is the world's largest bird", "Male emu incubates the eggs for 7-8 weeks", "The Emu has two sets of eyelids", "The Emu can run up to 48km per hour"],
["Which of the following is NOT a term for a group of Kangaroos?",  "Phalanx", "Mob", "Troop", "Court"],
["What was the first Australian to have his/her voice broadcast from space to Earth?",  "Slim Dusty", "Kylie Minogue", "Yothu Yindi", "Joan Sutherland"],
["The 'Gangland murders' carried out between 1995-2009 were associated with which union?",  "Painters & Dockers Union", "Australian Ruby Union", "Union Jack", "Australian Workers Union"],
["Who of the following published the children's book 'Hooky the Cripple'?",  "Chopper Read", "Ned Kelly", "Sam Poo", "Carl Williams"],
["What is the family name of Australian Idol's Andrew G?",  "Günsberg", "Gugliano", "Gambino", "Gautstafr"],
["In what year was the Australian Flag first flown?",  "1901", "1900", "1788", "1872"],
["Which of the following is NOT a protocol of the Australian National Flag?",  "The flag may be worn as apparel", "Raise the flag quickly & lower it slowly", "One flag per pole", "The flag should be flown at night only when it is lit"],
["Who wrote 'Advance Australia Fair'?",  "Peter McCormick", "Slim Dusty", "Peter Lalor", "Rolf Harris"],
["How many points on the McArthur Forest Fire Danger Index constitutes a Severe Fire Weather day?", "50-74", "12-24", "75-99", "100+"],
["Which anthem is played at the beginning of Australian ceremonies when The Queen is in Australia?",  "God Save the Queen", "Advance Australia Fair", "One Nation under God", "The Star Spangled Banner"],
["What course of action is recommended after issuing of a Catastrophic Fire Warning?",  "Evacuate before any fires start", "Wait to hear whether any fires start & then evacuate", "Stay & defend your property", "Wait for fire service to come & evacuate you"],
["How many stairs in the Eureka Climb?",  "1958", "1895", "1599", "1624"],
["In what year was the Aboriginal Flag formally recognised by Federal legislation?",  "1995", "1967", "1971", "1986"],
["In what year was the Torres Strait Islander Flag formally recognised by Federal legislation?",  "1995", "1956", "1972", "2005"],
["Where was the Aboriginal Flag originally displayed?",  "Victoria Square, Adelaide, 1971", "Aboriginal Tent Embassy, Canberra, 1972", "National Sorry Day, Canberra, 2003", "Uluru, NT, 1967"],
["Which colour is on the top half of the Aboriginal Flag (behind the sun)?",  "Black", "Red", "Yellow", "Green"],
["Which town is closest to Dangar Falls?",  "Dorrigo, NSW", "Armidale, NSW", "Appollo Bay, VIC", "Derwent, TAS"],
["Which Australian photojournalist co-produced 'Journeys to the Ends of the Earth'?",  "David Adams", "Mike Leyland", "Kan Parish", "Steve Irwin"],
["Which Aboriginal anti-nuclear protestor was arrested for stealing the Australian Coat of Arms from Parliament House?",  "Kevin Buzzacott", "Kyle Sandilands", "Peter Garrett", "Nicola Paris"],
["What was the name of the ship that photographer Helmut Newton came to Australia on as a WW2 POW?",  "Queen Mary", "Queen Elizabeth", "The Brittania", "The Eastern Queen"],
["Which Australian photographer started out as an apprentice gunsmith in Adelaide?",  "Ken Parish", "Bill Henson", "Charles P. Mountford", "Richard Daintree"],
["Who was the architect of Sydney's Queen Victoria Building?",  "George McRae", "Barrie Marshall", "William Pitt", "Howard Raggatt"],
["In what architectural style was the National Museum of Canberra designed?",  "Postmodern", "Victorian", "Colonial", "Inter-war Functionalism"],
["Which 1997 failed building implosion caused death & injury in Canberra?",  "Royal Canberra Hospital", "Old Parliament House", "Black Mountain Tower", "Immigration Bridge"],
["Who was the first Australian fashion designer to launch a 'ready-to-wear' line in Paris?",  "Collette Dinnigan", "Pru Acton", "Joe Saba", "Carla Zampatti"],
["How many languages does SBS Radio broadcast in?", "65-75", "20-30", "30-40", "45-55"],
["Which Australian fashion designer was Chairman of the SBS for a decade?",  "Carla Zampatti", "Joe Saba", "Akira Isagawa", "Pru Acton"],
["Which Australian band had the hit song 'Help is on its way'?", "Little River Band", "AC/DC", "The Divinyls", "Mental as Anything"],
["Which song was the first played in colour transmission by Countdown?",  "Horror Movie", "Raindrops Keep Falling On My Head", "Up There Cazaly", "Computer Games"],
["Which Australian town is ranked 5th for UFO sightings in the world?",  "Wycliffe Well, NT", "Clayton, VIC", "Picton, NSW", "Caboulture, QLD"],
["Which Australian town is ranked 2nd for UFO sightings in the world?",  "Clayton, VIC", "Wycliffe Well, WA", "Dodges Ferry, TAS", "American River, KI"],
["Which town has the HMAS Otway submarine installed on their main street?",  "Holbrook, NSW", "Apollo Bay, Vic", "Dubbo NSW", "Barcaldine, QLD"],
["Which of the following means 'place of good drink' in an Aboriginal dialect?",  "Ettamogah", "Kangiangi", "Clybucca", "Bermagui"],
["During which 1971 sporting event was a State of Emergency declared for a month in QLD?",  "Springbok Tour", "Mount Panorama", "Cronulla Surf Carnival", "Diggers v GI football match"],
["Where are nuclear weapons now stored in Australia?",  "Nuclear weapons are not stored in Australia", "Woomera", "Maralinga", "Pine Gap"],
["What did the 1960's Aldermaston Relay Walk protest?",  "The effects of nuclear testing in the Pacific", "The under funding of sport", "Vietnam War conscription", "The 40 hour week"],
["Members from which group were charged with trespass on Pine Gap in 2006?",  "Christians Against All Terrorism", "Freemantle Anti-Nuclear Group", "ACT Feminist Anti-Nuclear Group", "Nuclear Free Australia"],
["Approximately what percentage of the world's known Uranium reserves are in Australia?",  "20-25%", "40-45%", "15-19%", "0-5%"],
["How many nuclear power generators are there in Australia?",  "0", "1", "3", "5"],
["Which genre best describes the 2006 movie 'Kenny'?",  "Mockumentary", "Documentary", "Comedy", "Action"],
["Which was the first Australian movie to use the widescreen anamorphic lens?",  "Mad Max", "The Story of the Kelly Gang", "Jewel of the Pacific", "This Woman Is Not a Car"],
["Which 1976 film was set in the Coorong, SA?",  "Storm Boy", "Caddie", "Mad Dog Morgan", "The Devil's Playground"],
["Which of the following is NOT true of the 1988 movie 'Young Einstein'?",  "Young Einstein's pet Chicken Little, discovers gravity", "It had 'cat pies'", "Einstein splits a beer atom with a chisel", "Rock & roll is used to save the world from a nuclear reactor"],
["Which Australian observatory is featured in the 2000 movie 'The Dish'?",  "Parkes", "Mount Stromlo", "Cangaroo", "Sydney"],
["Which space mission was featured in the 2000 movie 'The Dish'?",  "Apollo 11", "Apollo 13", "Endeavour", "Challenger 2"],
["Where is the world's single largest uranium deposit?",  "Olympic Dam, SA", "Jabiluka, NT", "Ranger Uranium Mine, NT", "Jervis Bay, NSW"],
["Which mine is the greatest user of underground water in Australia?",  "Olympic Dam, SA", "The Sydney Aquatic Centre, NSW", "Snowy Mountains Hydro-Electric Scheme, NSW", "Ranger Uranium Mine, NT"],
["How large is the Western Plateau?",  "2,700,000 km sq", "2700 km sq", "27,000 km sq", "227,000 km sq"],
["Which 70-80's band had the hit 'If You Leave Me, Can I Come Too?'",  "Mental as Anything", "Rose Tattoo", "The Divinyls", "INXS"],
["Which of the following is NOT true of the Men at Work song 'Down Under'?",  "Played during the credits for the movie 'Kenny'", "It was sung by the Red Choir", "It is featured in the game 'Saint's Row 2'", "The flute part is allegedly based on the children's rhyme 'Kookaburra'"]];