var questions = [["In which country is Tora Bora?", "Afghanistan"],
["Which country is home to the last remaining Balkan lynx?", "Albania"],
["In terms of land area, which is the largest country on the Mediterranean Sea?", "Algiera"],
["Which country has the second-highest life expectancy in the world?", "Andorra"],
["Which country has the highest economic growth rate in Africa?", "Angola"],
["Which country name means 'ancient' and 'bearded'?", "Antigua & Barbuda"],
["Which is the world's eighth largest country?", "Argentina"],
["Which Kingdom was the first state to adopt Christianity?", "Armenia"],
["The waters of which country contain the only living thing visible from space?", "Australia"],
["Which country currently produces more than half of its power through hydropower?", "Austria"],
["In which country is the Walled City of Baku?", "Azerbaijan"],
["Which country's coat of arms contains a marlin and a flamingo?", "The Bahamas"],
["Which was the fist Arab country to institute Unemployment Benefits?", "Bahrain"],
["Which country suffered the most severe flooding in modern world history in 1998?", "Bangladesh"],
["Which country was called 'Ichirouganaim' by its indigenous inhabitants?", "Barbados"],
["Minsk is the capital of which country?", "Belarus"],
["A Roman Catholic priest from which country is credited with the Big Bang theory?", "Belgium"],
["Which is the only nation in Central America with a British colonial heritage?", "Belize"],
["Which country was once nicknamed the 'black Sparta'?", "Benin"],
["Which country name means 'Land of the Thunder Dragon'?", "Bhutan"],
["Which country contains the highest capital in the world?", "Bolivia"],
["Which country was formed in the wake of the Srebrenica Massacre?", "Bosnia & Herzegovina"],
["Which country is largely covered by the Kalahari Desert?", "Botswana"],
["Which is the only Portuguese-speaking country in the Americas?", "Brazil"],
["Which country publishes the 'Borneo Bulletin'?", "Brunei"],
["Which European country ranks first in I.T. certified specialists per head?", "Bulgaria"],
["Which country name means 'the land of upright people'?", "Burkina Faso"],
["Which country has the lowest per capita GDP of any nation in the world?", "Burundi"],
["In which country is the Tonle Sap Biosphere Reserve?", "Cambodia"],
["Which country is described by its government as 'Africa in miniature'?", "Cameroon"],
["The flag of which country features the maple leaf?", "Canada"],
["What country is Praia the capital of?", "Cape Verde"],
["Which African country was claimed world leader in sustainable development in The Ecologist (2001)?", "Central African Republic"],
["Which country is sometimes referred to as the 'Dead Heart of Africa'?", "Chad"],
["Which country hosted the Cybersyn real-time computer-controlled planned economy?", "Chile"],
["Which country won the most gold medals at the 2008 Summer Olympics?", "China"],
["What country is Bogota the capital of?", "Colombia"],
["Which country is the world's largest producer of Ylang-ylang?", "Comoros"],
["In which country would you find Pygmy slaves?", "Republic of the Congo"],
["Kinshasa is the capital of which country?", "Democratic Republic of Congo"],
["Which country name means 'Rich Coast'?", "Costa Rica"],
["Which country's football team is nicknamed Les Éléphants (The Elephants)?", "Cote d'Ivoire"],
["Which country won the 2009 Men's Handball world championship?", "Croatia"],
["Which country jails citizens for buying computers without government permission?", "Cuba"],
["Which country did Turkey invade in 1974?", "Cyprus"],
["The Velvet Divorce the resulted in Slavakia and which other country?", "Czech Republic"],
["In which country are the Jelling Stones?", "Denmark"],
[".dj is the country code top-level domain (ccTLD) owned by which country?", "Djibouti"],
["Which country was named by Columbus as the Italian word for Sunday?", "Dominica"],
["In which country did the Parsley Massacre occur?",  "Dominican Republic"],
["In which country was the movie 'Balibo' set?", "East Timor"],
["The waters of which country contain the Galápagos Islands?", "Ecuador"],
["Which country is home to the largest city in Africa and the Middle East?", "Egypt"],
["Which country is the smallest and most densely populated in Central America?", "El Salvador"],
["The coat of arms of which country features the silk-cotton or god tree?", "Equatorial Guinea"],
["Which country's coat of arms features a camel?", "Eritrea"],
["Which country's currency is the kroon?", "Estonia"],
["Which country is home to the oldest Muslim settlement in Africa?", "Ethiopia"],
["Which country was the first nation ever to be expelled from the Pacific Islands Forum?", "Fiji"],
["In which country are the Astuvansalmi rock paintings?",  "Finland"],
["Which country has more international visitors than any other?", "France"],
["Which country has up to 60,000 forest elephants?", "Gabon"],
["Which is the smallest country on the continent of Africa?", "The Gambia"],
["A luger from which country was killed during the 2010 Winter Olympics?", "Georgia"],
["Which country was divided until 1989 by a wall between the communist East and the democratic West?", "Germany"],
["Which country name means Warrior King?", "Ghana"],
["Which country is the birthplace of democracy & the Olympic Games?", "Greece"],
["Which country was the target of 1983 Operation Urgent Fury?", "Grenada"],
["Which country's president was overthrown by a CIA coup in 1954?", "Guatemala"],
["What country is Conakry the capital of? ", "Guinea"],
["The calabash is the primary musical instrument of which country?", "Guinea-Bissau"],
["Which country is also known as 'The Land Of Many Waters'?", "Guyana"],
["Which country was the first black-led republic?", "Haiti"],
["The Lempira is the currency of which country?", "Honduras"],
["Which country is home to the largest natural grasslands in Europe?", "Hungary"],
["Which country's currency is the króna?", "Iceland"],
["Which is the world's 2nd most populous country?", "India"],
["Which country has the most active volcanos?", "Indonesia"],
["Which country was formerly known as Persia?", "Iran"],
["The Euphrates and Tigris Rivers run through the centre of which country?", "Iraq"],
["Which country was known to the Romans as Hibernia?", "Ireland"],
["Which country is the world's only predominantly Jewish state?", "Israel"],
["Which country is the birthplace of opera?", "Italy"],
["The coat of arms of which country features a crocodile & 5 pineapples?", "Jamaica"],
["Which country has the highest life expectancy?", "Japan"],
["In which country was the original Philadelphia?", "Jordan"],
["Which country's name was part of the title of a Sacha Baron Cohen film?", "Kazakhstan"],
["Which country is Nairobi the capital of?", "Kenya"],
["Which country moved the dateline to be the first country to see the dawn of the third millennium?", "Kiribati"],
["The coat of arms of which country features a hydroelectric power plant?", "North Korea"],
["In which country did the Miracle on the Han River occur?", "South Korea"],
["Which country is Pristina the capital of?", "Kosovo"],
["Which country name is derived from Arabic meaning fortress built near water?", "Kuwait"],
["Which country's flag symbolizes the forty tribes of Manas?", "Kyrgyzstan"],
["Which country was once known as the 'Switzerland of the East'?", "Lebanon"],
["Which country's national motto is 'Peace, Rain, Prosperity'?", "Lesotho"],
["Which country was founded and colonized for freed American slaves?", "Liberia"],
["Which country's flag is a single colour with no other embellishments?", "Libya"],
["Which is the only german-speaking country not to share a border with Germany?", "Liechtenstein"],
["Which country was the largest in Europe during the 14th century?", "Lithuania"],
["Which country is the world's only remaining sovereign Grand Duchy?", "Luxembourg"],
["The flag of which country features the Vergina Sun?", "Macedonia"],
["Which country is the 4th largest island in the world?", "Madagascar"],
["Which country has a lake known as the 'calendar' lake?", "Malawi"],
["In which country are the Patronas Towers?", "Malaysia"],
["Which country is to become the first carbon-neutral economy?", "Maldives"],
["In which country is Timbuktu?", "Mali"],
["In which country are the Megalithic Temples?", "Malta"],
["Which country was the site of the largest nuclear test ever conducted by the United States?", "Marshall Islands"],
["Which country's feminine ideal of obesity results in force-feeding?", "Mauritania"],
["Which country was home to the dodo bird prior to extinction?", "Mauritius"],
["Which country's coat of arms includes a Golden Eagle on a cactus eating a snake?", "Mexico"],
[".fm is the country code top-level domain (ccTLD) owned by which country?",  "Federated States of Micronesia"],
["Which country is in the 2005 Guiness World Records for the largest wine collection?", "Moldova"],
["Which is the world's most densely populated country?", "Monaco"],
["Which country is named after the largest contiguous empire in the history of the world?", "Mongolia"],
["Which country means 'Black Mountain'?", "Montenegro"],
["The Barbary Lion is often considered the national emblem of which country?", "Morocco"],
["Which country's coat of arms features an AK-47 crossed with a hoe, and a book?", "Mozambique"],
["Which country was most devastated in 2008 by Cyclone Nargis?", "Myanmar"],
["Which country is known as the 'the land God made in anger'?", "Namibia"],
["Which country is the world's smallest island nation?", "Nauru"],
["Which country has 8 of the top 10 highest mountains of the world?", "Nepal"],
["The people of which country are known by the demonym 'Dutch'?", "Netherlands"],
["Which country's indigenous language name 'Aotearoa' means 'Land of the Long White Cloud'?", "New Zealand"],
["Which is Managua the capital of?", "Nicaragua"],
["In which country is the Uranium Highway?", "Niger"],
["Which is the most populous country in Africa?", "Nigeria"],
["Which country ranks as wealthiest with the IMF?", "Norway"],
["Which country held the first site ever deleted from UNESCO's World Heritage list?", "Oman"],
["Which country is the only Muslim-majority nuclear state?", "Pakistan"],
["Which country is the site of the oldest known burial ceremony in Oceania?", "Palau"],
["Which country has over 850 indigenous languages?", "Papua New Guinea"],
["Which country is sometimes referred to as the 'Heart of America'?", "Paraguay"],
["In which country is Machu Picchu, the 'Lost City of the Incas'?", "Peru"],
["Which country is the world's second-biggest geothermal producer behind the US?", "Philippines"],
["Which country lost the highest percentage of its citizens during WWII?", "Poland"],
["In which country was the Carnation Revolution?", "Portugal"],
["Which country has the highest GDP per capita in the world?", "Qatar"],
["The oldest human remains in Europe were found in which country?", "Romania"],
["Which country was responsible for the largest ever nuclear bomb explosion?", "Russia"],
["Which country is known as the Land of a Thousand Hills?", "Rwanda"],
["In which country is the fort known as 'The Gibraltar of the West Indies'?", "Saint Kitts and Nevis"],
["Which island nation has been the home of Nobel laureates Arthur Lewis & Derek Walcott?", "Saint Lucia"],
["What country is Kingstown the capital of?", "Saint Vincent & the Grenadines"],
["Which country became independent from New Zealand in 1962?", "Samoa"],
["What is the oldest soverign state in the world?", "San Marino"],
["Which country has the world's oldest constitution still in effect?", "San Marino"],
[".st is the Internet country code top-level domain (ccTLD) owned by which country?", "Sao Tome & Principe"],
["Which country is often called 'The Land of the Two Holy Mosques'?", "Saudi Arabia"],
["Which country is at GPS coordinates 14 00 N, 14 00 W?", "Senegal"],
["Which country was the second state in Europe to abolish feudalism and serfdom?", "Serbia"],
["Which country has the smallest population of any African state?", "Seychelles"],
["The Krio language is spoken by 97% of which country's population?", "Sierra Leone"],
["What country is the smallest nation in South East Asia?", "Singapore"],
["Which country is called the 'Tatra Tiger'?", "Slovakia"],
["In which country are edible dormice are consumed?", "Slovenia"],
["During WWII, in which country was Operation Watchtower carried out?", "Solomon Islands"],
["Which country's shoreline is believed by UNEP to be a dumping ground of radio-active waste?", "Somalia"],
["Which country held its first multi-racial elections in 1994?", "South Africa"],
["Which country is the traditional home of bullfighting?", "Spain"],
["Which country was the first in the world to elect a female Prime Minister?", "Sri Lanka"],
["Which country is home to the Dinka people?", "Sudan"],
["In which South American country does a mosque and a synagogue sit side by side?", "Suriname"],
["Which country has the highest HIV infection rate in the world?", "Swaziland"],
["Which country is connected to Denmark by the Øresundsbron Bridge?", "Sweden"],
["Which country's traditional motto is 'one for all, all for one'?", "Switzerland"],
["Which country has been under Emergency Law since 1962?", "Syria"],
["In which country is Taipei 101?", "Taiwan"],
["Which nation's currency is the somoni?", "Tajikistan"],
["Which country is famous for the art styles Tingatinga and Makonde?", "Tanzania"],
["Which country is the world's largest rice exporter?", "Thailand"],
["In which country are the Taberma houses?", "Togo"],
["Which country has heart and banana shaped stamps?", "Tonga"],
["From which country did Calypso music originate?", "Trinidad & Tobago"],
["Which is the northernmost country in Africa?", "Tunisia"],
["Which country's national sport is oiled wrestling?", "Turkey"],
["Which country banned satellite dishes, beards, long hair, ballet, opera & recorded music?", "Turkmenistan"],
[".tv is the Internet country code top-level domain (ccTLD) owned by which country?", "Tuvalu"],
["In which country is Lake Kyoga?", "Uganda"],
["In which country claims The Holodomor was genocide against its citizens?", "Ukraine"],
["The coast of which country was known as the 'Pirate Coast'?", "United Arab Emirates"],
["Which was the world's first industralized country?", "United Kingdom"],
["Which country first put men on the Moon?", "United States of America"],
["A composer from which country wrote the famous Tango, La Cumparsita?", "Uruguay"],
["Which country,  formerly in the Soviet Union has a Korean population forcibly relocated by Stalin?", "Uzbekistan"],
["Which country worships Prince Philip as a divine, pale-skinned son of a mountain spirit?", "Vanuatu"],
["Which country is protected by the Swiss Guard?", "Vatican City"], 
["Which country has the tallest waterfall in the world?", "Venezuela"], 
["In which country is Hồ Chí Minh City?", "Vietnam"], 
["Which is the poorest country in the Arab world?", "Yemen"], 
["Which is the only country in Africa that manufactures mobile phones?", "Zambia"], 
["In which country has 60% of the wildlife has died since 2000?", "Zimbabwe"],
["Through which country can you sail from the Caribbean Sea to the North Pacific Ocean?", "Panama"]];